import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { PrivacyComponent } from './pages/juridisch/privacy/privacy.component';
import { TermsComponent } from './pages/juridisch/terms/terms.component';
import { ContactComponent } from './pages/contact/contact.component';
import { NotFoundComponent } from './components/not-found/not-found.component';
import { RemoveAccountComponent } from './pages/account/remove/removeAccount.component';
import { WatIsEenAnytimer } from './pages/blogs/begrippen/wat-is-een-anytimer/wat-is-een-anytimer.component';
import { BlogComponent } from './pages/blog/blog.component';
import { DrankspellenComponent } from './pages/blogs/inspiratie/drankspellen/drankspellen.component';
import { WatIsEenAdtjeComponent } from './pages/blogs/begrippen/wat-is-een-adtje/wat-is-een-adtje.component';
import { WatIsDeBestAdtTimerComponent } from './pages/blogs/inspiratie/wat-is-de-beste-adt-timer/wat-is-de-beste-adt-timer.component';
import { MagJeEenAnyttimerWeigerenComponent } from './pages/blogs/weetjes/mag-je-een-anytimer-weigeren/mag-je-een-anytimer-weigeren.component';
import { AnytimersWhatsappNotitiesComponent } from './pages/blogs/weetjes/anytimers-bijhouden-whatsapp-notities/anytimers-bijhouden-whatsapp-notities.component';
import { HuisavondideeenComponent } from './pages/blogs/inspiratie/huisavondideeen/huisavondideeen.component';
import { JeuDeBierComponent } from './pages/blogs/drankspelletjes/jeu-de-bier/jeu-de-bier.component';
import { BlogCategoryComponent } from './pages/blog-category/blog-category.component';
import { MarioBarfComponent } from './pages/blogs/drankspelletjes/mario-barf/mario-barf.component';
import { TrekJeBakManiaComponent } from './pages/blogs/drankspelletjes/trek-je-bak-mania/trek-je-bak-mania.component';
import { ThirtySecondsComponent } from './pages/blogs/drankspelletjes/30-seconds/30-seconds.component';
import { KingsenComponent } from './pages/blogs/drankspelletjes/kingsen/kingsen.component';
import { StressPongComponent } from './pages/blogs/drankspelletjes/stress-pong/stress-pong.component';
import { FuckTheDealerComponent } from './pages/blogs/drankspelletjes/fuck-the-dealer/fuck-the-dealer.component';
import { MexenComponent } from './pages/blogs/drankspelletjes/mexen/mexen.component';
import { BakplatenComponent } from './pages/blogs/drankspelletjes/bakplaten/bakplaten.component';
import { DePaardenraceComponent } from './pages/blogs/drankspelletjes/de-paardenrace/de-paardenrace.component';
import { RingOfFireComponent } from './pages/blogs/drankspelletjes/ring-of-fire/ring-of-fire.component';
import { MijnenveldComponent } from './pages/blogs/drankspelletjes/mijnenveld/mijnenveld.component';
import { StefStuntpilootComponent } from './pages/blogs/drankspelletjes/stef-stuntpiloot/stef-stuntpiloot.component';
import { VingerenComponent } from './pages/blogs/drankspelletjes/vingeren/vingeren.component';
import { VikingenComponent } from './pages/blogs/drankspelletjes/vikingen/vikingen.component';
import { ZeeslagComponent } from './pages/blogs/drankspelletjes/zeeslag/zeeslag.component';
import { KusjeGevenComponent } from './pages/blogs/drankspelletjes/kusje-geven/kusje-geven.component';
import { BussenComponent } from './pages/blogs/drankspelletjes/bussen/bussen.component';
import { HogerLagerComponent } from './pages/blogs/drankspelletjes/hoger-lager/hoger-lager.component';
import { KrokodillenspelComponent } from './pages/blogs/drankspelletjes/krokodillenspel/krokodillenspel.component';
import { BlogTermComponent } from './pages/blog-term/blog-term.component';

export const routes: Routes = [
  { path: '', component: HomeComponent, title: 'AnyTimerApp - De app om je anytimers in bij te houden' },
  { path: 'privacy', component: PrivacyComponent, title: 'Privacybeleid AnyTimerApp - AVG-Conform & Veilig' },
  { path: 'remove-account', component: RemoveAccountComponent, title: 'Account Verwijderen AnyTimerApp - Stap-voor-Stap Gids' },
  { path: 'terms', component: TermsComponent, title: 'Gebruiksvoorwaarden AnyTimerApp - Regels & Voorwaarden' },
  { path: 'contact', component: ContactComponent, title: 'Contact AnyTimerApp - Vragen, Feedback & Samenwerking' },
  { path: 'blog', component: BlogComponent, title: 'AnyTimerApp Blog - Tips, Ideeën & Gidsen' },
  { path: 'blog/begrippen', component: BlogCategoryComponent, title: 'Anytimer Begrippen Uitgelegd | AnyTimerApp', data: { category: 'Begrippen' } },
  { path: 'blog/inspiratie', component: BlogCategoryComponent, title: 'Inspiratie voor een Leuke Avond | AnyTimerApp', data: { category: 'Inspiratie' } },
  { path: 'blog/weetjes', component: BlogCategoryComponent, title: 'Anytimer Weetjes & Regels | AnyTimerApp', data: { category: 'Weetjes' } },
  { path: 'blog/drankspelletjes', component: BlogCategoryComponent, title: 'Drankspelletjes: Spelregels & Tips | AnyTimerApp', data: { category: 'Drankspelletjes' } },
  { path: 'drankspellen', component: DrankspellenComponent, title: 'Top 10 Leukste Drankspellen voor een Gezellige Avond | AnyTimerApp' },
  { path: 'wat-is-een-anytimer', component: WatIsEenAnytimer, title: 'Wat is een Anytimer? - Gids & Uitleg | AnyTimerApp' },
  { path: 'wat-is-een-adtje', component: WatIsEenAdtjeComponent, title: 'Wat is een Adtje? - Gids & Uitleg | AnyTimerApp' },
  { path: 'wat-is-de-beste-adt-timer', component: WatIsDeBestAdtTimerComponent, title: 'Wat is de Beste Adt Timer? - Gids & Opties | AnyTimerApp' },
  { path: 'mag-je-een-anytimer-weigeren', component: MagJeEenAnyttimerWeigerenComponent, title: 'Mag je een Anytimer Weigeren? - Regels & Gevolgen | AnyTimerApp' },
  { path: 'anytimers-bijhouden-whatsapp-notities', component: AnytimersWhatsappNotitiesComponent, title: 'Waarom je Anytimers niet in WhatsApp of Notities Bijhoudt | AnyTimerApp' },
  { path: 'huisavondideeen', component: HuisavondideeenComponent, title: 'Top 10 Leuke Huisavondideeën | AnyTimerApp' },
  { path: 'blog/drankspelletjes/jeu-de-bier', component: JeuDeBierComponent, title: 'Jeu de Bier - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/mario-barf', component: MarioBarfComponent, title: 'Mario Barf - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/trek-je-bak-mania', component: TrekJeBakManiaComponent, title: 'Trek je Bak Mania - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/30-seconds', component: ThirtySecondsComponent, title: '30 Seconds - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/kingsen', component: KingsenComponent, title: 'Kingsen - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/stress-pong', component: StressPongComponent, title: 'Stress Pong - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/fuck-the-dealer', component: FuckTheDealerComponent, title: 'Fuck the Dealer - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/mexen', component: MexenComponent, title: 'Mexen - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/bakplaten', component: BakplatenComponent, title: 'Bakplaten - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/de-paardenrace', component: DePaardenraceComponent, title: 'De Paardenrace - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/ring-of-fire', component: RingOfFireComponent, title: 'Ring of fire - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/mijnenveld', component: MijnenveldComponent, title: 'Mijnenveld - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/stef-stuntpiloot', component: StefStuntpilootComponent, title: 'Stef stuntpiloot - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/vingeren', component: VingerenComponent, title: 'Vingeren - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/vikingen', component: VikingenComponent, title: 'Vikingen - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/zeeslag', component: ZeeslagComponent, title: 'Zeeslag - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/kusje-geven', component: KusjeGevenComponent, title: 'Kusje geven - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/bussen', component: BussenComponent, title: 'Bussen - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/hoger-lager', component: HogerLagerComponent, title: 'Hoger lager - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/krokodillenspel', component: KrokodillenspelComponent, title: 'Krokodillenspel - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/begrippen/ab-actis', component: BlogTermComponent, title: 'Wat betekent: Ab actis?', data: { slug: 'ab-actis' } },
  { path: 'blog/begrippen/abbo', component: BlogTermComponent, title: 'Wat betekent: Abbo?', data: { slug: 'abbo' } },
  { path: 'blog/begrippen/adten', component: BlogTermComponent, title: 'Wat betekent: Adten?', data: { slug: 'adten' } },
  { path: 'blog/begrippen/adtje-des', component: BlogTermComponent, title: 'Wat betekent: Adtje des?', data: { slug: 'adtje-des' } },
  { path: 'blog/begrippen/adtje-herhaling', component: BlogTermComponent, title: 'Wat betekent: Adtje herhaling?', data: { slug: 'adtje-herhaling' } },
  { path: 'blog/begrippen/adtje-kratje', component: BlogTermComponent, title: 'Wat betekent: Adtje kratje?', data: { slug: 'adtje-kratje' } },
  { path: 'blog/begrippen/adtje-solidair', component: BlogTermComponent, title: 'Wat betekent: Adtje solidair?', data: { slug: 'adtje-solidair' } },
  { path: 'blog/begrippen/adulting', component: BlogTermComponent, title: 'Wat betekent: Adulting?', data: { slug: 'adulting' } },
  { path: 'blog/begrippen/afk', component: BlogTermComponent, title: 'Wat betekent: AFK?', data: { slug: 'afk' } },
  { path: 'blog/begrippen/afko', component: BlogTermComponent, title: 'Wat betekent: Afko?', data: { slug: 'afko' } },
  { path: 'blog/begrippen/afpilsen', component: BlogTermComponent, title: 'Wat betekent: Afpilsen?', data: { slug: 'afpilsen' } },
  { path: 'blog/begrippen/afstubo', component: BlogTermComponent, title: 'Wat betekent: Afstubo?', data: { slug: 'afstubo' } },
  { path: 'blog/begrippen/afterparty', component: BlogTermComponent, title: 'Wat betekent: Afterparty?', data: { slug: 'afterparty' } },
  { path: 'blog/begrippen/airfryer', component: BlogTermComponent, title: 'Wat betekent: Airfryer?', data: { slug: 'airfryer' } },
  { path: 'blog/begrippen/al', component: BlogTermComponent, title: 'Wat betekent: AL?', data: { slug: 'al' } },
  { path: 'blog/begrippen/algorithm', component: BlogTermComponent, title: 'Wat betekent: Algorithm?', data: { slug: 'algorithm' } },
  { path: 'blog/begrippen/all-nighter', component: BlogTermComponent, title: 'Wat betekent: All-nighter?', data: { slug: 'all-nighter' } },
  { path: 'blog/begrippen/almanak', component: BlogTermComponent, title: 'Wat betekent: Almanak?', data: { slug: 'almanak' } },
  { path: 'blog/begrippen/alt-account', component: BlogTermComponent, title: 'Wat betekent: Alt account?', data: { slug: 'alt-account' } },
  { path: 'blog/begrippen/alv', component: BlogTermComponent, title: 'Wat betekent: ALV?', data: { slug: 'alv' } },
  { path: 'blog/begrippen/ambu', component: BlogTermComponent, title: 'Wat betekent: Ambu?', data: { slug: 'ambu' } },
  { path: 'blog/begrippen/amice', component: BlogTermComponent, title: 'Wat betekent: Amice?', data: { slug: 'amice' } },
  { path: 'blog/begrippen/arbeider', component: BlogTermComponent, title: 'Wat betekent: Arbeider?', data: { slug: 'arbeider' } },
  { path: 'blog/begrippen/asap', component: BlogTermComponent, title: 'Wat betekent: ASAP?', data: { slug: 'asap' } },
  { path: 'blog/begrippen/assessor', component: BlogTermComponent, title: 'Wat betekent: Assessor?', data: { slug: 'assessor' } },
  { path: 'blog/begrippen/assignment', component: BlogTermComponent, title: 'Wat betekent: Assignment?', data: { slug: 'assignment' } },
  { path: 'blog/begrippen/ate', component: BlogTermComponent, title: 'Wat betekent: Ate?', data: { slug: 'ate' } },
  { path: 'blog/begrippen/aura', component: BlogTermComponent, title: 'Wat betekent: Aura?', data: { slug: 'aura' } },
  { path: 'blog/begrippen/baco', component: BlogTermComponent, title: 'Wat betekent: Baco?', data: { slug: 'baco' } },
  { path: 'blog/begrippen/bak-trekken', component: BlogTermComponent, title: 'Wat betekent: Bak trekken?', data: { slug: 'bak-trekken' } },
  { path: 'blog/begrippen/bakken-vouwen', component: BlogTermComponent, title: 'Wat betekent: Bakken vouwen?', data: { slug: 'bakken-vouwen' } },
  { path: 'blog/begrippen/bal', component: BlogTermComponent, title: 'Wat betekent: Bal?', data: { slug: 'bal' } },
  { path: 'blog/begrippen/barco', component: BlogTermComponent, title: 'Wat betekent: Barco?', data: { slug: 'barco' } },
  { path: 'blog/begrippen/barf', component: BlogTermComponent, title: 'Wat betekent: Barf?', data: { slug: 'barf' } },
  { path: 'blog/begrippen/based', component: BlogTermComponent, title: 'Wat betekent: Based?', data: { slug: 'based' } },
  { path: 'blog/begrippen/batsen', component: BlogTermComponent, title: 'Wat betekent: Batsen?', data: { slug: 'batsen' } },
  { path: 'blog/begrippen/beer-pong', component: BlogTermComponent, title: 'Wat betekent: Beer pong?', data: { slug: 'beer-pong' } },
  { path: 'blog/begrippen/before-and-after', component: BlogTermComponent, title: 'Wat betekent: Before and after?', data: { slug: 'before-and-after' } },
  { path: 'blog/begrippen/beige-flag', component: BlogTermComponent, title: 'Wat betekent: Beige flag?', data: { slug: 'beige-flag' } },
  { path: 'blog/begrippen/benching', component: BlogTermComponent, title: 'Wat betekent: Benching?', data: { slug: 'benching' } },
  { path: 'blog/begrippen/berig', component: BlogTermComponent, title: 'Wat betekent: Berig?', data: { slug: 'berig' } },
  { path: 'blog/begrippen/bestuur', component: BlogTermComponent, title: 'Wat betekent: Bestuur?', data: { slug: 'bestuur' } },
  { path: 'blog/begrippen/bet', component: BlogTermComponent, title: 'Wat betekent: Bet?', data: { slug: 'bet' } },
  { path: 'blog/begrippen/bij', component: BlogTermComponent, title: 'Wat betekent: Bij?', data: { slug: 'bij' } },
  { path: 'blog/begrippen/bits', component: BlogTermComponent, title: 'Wat betekent: Bits?', data: { slug: 'bits' } },
  { path: 'blog/begrippen/blackout', component: BlogTermComponent, title: 'Wat betekent: Blackout?', data: { slug: 'blackout' } },
  { path: 'blog/begrippen/bodem-leggen', component: BlogTermComponent, title: 'Wat betekent: Bodem leggen?', data: { slug: 'bodem-leggen' } },
  { path: 'blog/begrippen/body-count', component: BlogTermComponent, title: 'Wat betekent: Body count?', data: { slug: 'body-count' } },
  { path: 'blog/begrippen/bottoms-up', component: BlogTermComponent, title: 'Wat betekent: Bottoms up?', data: { slug: 'bottoms-up' } },
  { path: 'blog/begrippen/bouncer', component: BlogTermComponent, title: 'Wat betekent: Bouncer?', data: { slug: 'bouncer' } },
  { path: 'blog/begrippen/brainrot', component: BlogTermComponent, title: 'Wat betekent: Brainrot?', data: { slug: 'brainrot' } },
  { path: 'blog/begrippen/brak', component: BlogTermComponent, title: 'Wat betekent: Brak?', data: { slug: 'brak' } },
  { path: 'blog/begrippen/braken', component: BlogTermComponent, title: 'Wat betekent: Braken?', data: { slug: 'braken' } },
  { path: 'blog/begrippen/brassen', component: BlogTermComponent, title: 'Wat betekent: Brassen?', data: { slug: 'brassen' } },
  { path: 'blog/begrippen/breadcrumbing', component: BlogTermComponent, title: 'Wat betekent: Breadcrumbing?', data: { slug: 'breadcrumbing' } },
  { path: 'blog/begrippen/broke', component: BlogTermComponent, title: 'Wat betekent: Broke?', data: { slug: 'broke' } },
  { path: 'blog/begrippen/broke-student', component: BlogTermComponent, title: 'Wat betekent: Broke student?', data: { slug: 'broke-student' } },
  { path: 'blog/begrippen/bs', component: BlogTermComponent, title: 'Wat betekent: Bs?', data: { slug: 'bs' } },
  { path: 'blog/begrippen/btw', component: BlogTermComponent, title: 'Wat betekent: BTW?', data: { slug: 'btw' } },
  { path: 'blog/begrippen/bucket-list', component: BlogTermComponent, title: 'Wat betekent: Bucket list?', data: { slug: 'bucket-list' } },
  { path: 'blog/begrippen/bueno', component: BlogTermComponent, title: 'Wat betekent: Bueno?', data: { slug: 'bueno' } },
  { path: 'blog/begrippen/burger', component: BlogTermComponent, title: 'Wat betekent: Burger?', data: { slug: 'burger' } },
  { path: 'blog/begrippen/burgerrups', component: BlogTermComponent, title: 'Wat betekent: Burgerrups?', data: { slug: 'burgerrups' } },
  { path: 'blog/begrippen/burner-account', component: BlogTermComponent, title: 'Wat betekent: Burner account?', data: { slug: 'burner-account' } },
  { path: 'blog/begrippen/burnout', component: BlogTermComponent, title: 'Wat betekent: Burnout?', data: { slug: 'burnout' } },
  { path: 'blog/begrippen/bussin', component: BlogTermComponent, title: 'Wat betekent: Bussin?', data: { slug: 'bussin' } },
  { path: 'blog/begrippen/buying-a-round', component: BlogTermComponent, title: 'Wat betekent: Buying a round?', data: { slug: 'buying-a-round' } },
  { path: 'blog/begrippen/bv', component: BlogTermComponent, title: 'Wat betekent: Bv?', data: { slug: 'bv' } },
  { path: 'blog/begrippen/bvo', component: BlogTermComponent, title: 'Wat betekent: Bvo?', data: { slug: 'bvo' } },
  { path: 'blog/begrippen/byob', component: BlogTermComponent, title: 'Wat betekent: BYOB?', data: { slug: 'byob' } },
  { path: 'blog/begrippen/bsa', component: BlogTermComponent, title: 'Wat betekent: BSA?', data: { slug: 'bsa' } },
  { path: 'blog/begrippen/campus', component: BlogTermComponent, title: 'Wat betekent: Campus?', data: { slug: 'campus' } },
  { path: 'blog/begrippen/cancel-culture', component: BlogTermComponent, title: 'Wat betekent: Cancel culture?', data: { slug: 'cancel-culture' } },
  { path: 'blog/begrippen/cancelled', component: BlogTermComponent, title: 'Wat betekent: Cancelled?', data: { slug: 'cancelled' } },
  { path: 'blog/begrippen/canon-event', component: BlogTermComponent, title: 'Wat betekent: Canon event?', data: { slug: 'canon-event' } },
  { path: 'blog/begrippen/cap', component: BlogTermComponent, title: 'Wat betekent: Cap?', data: { slug: 'cap' } },
  { path: 'blog/begrippen/cappu', component: BlogTermComponent, title: 'Wat betekent: Cappu?', data: { slug: 'cappu' } },
  { path: 'blog/begrippen/catfish', component: BlogTermComponent, title: 'Wat betekent: Catfish?', data: { slug: 'catfish' } },
  { path: 'blog/begrippen/chaotic', component: BlogTermComponent, title: 'Wat betekent: Chaotic?', data: { slug: 'chaotic' } },
  { path: 'blog/begrippen/cheers', component: BlogTermComponent, title: 'Wat betekent: Cheers?', data: { slug: 'cheers' } },
  { path: 'blog/begrippen/chlam', component: BlogTermComponent, title: 'Wat betekent: Chlam?', data: { slug: 'chlam' } },
  { path: 'blog/begrippen/chronically-online', component: BlogTermComponent, title: 'Wat betekent: Chronically online?', data: { slug: 'chronically-online' } },
  { path: 'blog/begrippen/chug', component: BlogTermComponent, title: 'Wat betekent: Chug?', data: { slug: 'chug' } },
  { path: 'blog/begrippen/clickbait', component: BlogTermComponent, title: 'Wat betekent: Clickbait?', data: { slug: 'clickbait' } },
  { path: 'blog/begrippen/clout', component: BlogTermComponent, title: 'Wat betekent: Clout?', data: { slug: 'clout' } },
  { path: 'blog/begrippen/clubbing', component: BlogTermComponent, title: 'Wat betekent: Clubbing?', data: { slug: 'clubbing' } },
  { path: 'blog/begrippen/comfort-food', component: BlogTermComponent, title: 'Wat betekent: Comfort food?', data: { slug: 'comfort-food' } },
  { path: 'blog/begrippen/comfort-show', component: BlogTermComponent, title: 'Wat betekent: Comfort show?', data: { slug: 'comfort-show' } },
  { path: 'blog/begrippen/condo', component: BlogTermComponent, title: 'Wat betekent: Condo?', data: { slug: 'condo' } },
  { path: 'blog/begrippen/connie', component: BlogTermComponent, title: 'Wat betekent: Connie?', data: { slug: 'connie' } },
  { path: 'blog/begrippen/constitutieborrel', component: BlogTermComponent, title: 'Wat betekent: Constitutieborrel?', data: { slug: 'constitutieborrel' } },
  { path: 'blog/begrippen/content-creator', component: BlogTermComponent, title: 'Wat betekent: Content creator?', data: { slug: 'content-creator' } },
  { path: 'blog/begrippen/cooked', component: BlogTermComponent, title: 'Wat betekent: Cooked?', data: { slug: 'cooked' } },
  { path: 'blog/begrippen/core-memory', component: BlogTermComponent, title: 'Wat betekent: Core memory?', data: { slug: 'core-memory' } },
  { path: 'blog/begrippen/corps', component: BlogTermComponent, title: 'Wat betekent: Corps?', data: { slug: 'corps' } },
  { path: 'blog/begrippen/couple-goals', component: BlogTermComponent, title: 'Wat betekent: Couple goals?', data: { slug: 'couple-goals' } },
  { path: 'blog/begrippen/cover-charge', component: BlogTermComponent, title: 'Wat betekent: Cover charge?', data: { slug: 'cover-charge' } },
  { path: 'blog/begrippen/cramming', component: BlogTermComponent, title: 'Wat betekent: Cramming?', data: { slug: 'cramming' } },
  { path: 'blog/begrippen/crash-out', component: BlogTermComponent, title: 'Wat betekent: Crash out?', data: { slug: 'crash-out' } },
  { path: 'blog/begrippen/creator-economy', component: BlogTermComponent, title: 'Wat betekent: Creator economy?', data: { slug: 'creator-economy' } },
  { path: 'blog/begrippen/cringe', component: BlogTermComponent, title: 'Wat betekent: Cringe?', data: { slug: 'cringe' } },
  { path: 'blog/begrippen/cuffing-season', component: BlogTermComponent, title: 'Wat betekent: Cuffing season?', data: { slug: 'cuffing-season' } },
  { path: 'blog/begrippen/cursist', component: BlogTermComponent, title: 'Wat betekent: Cursist?', data: { slug: 'cursist' } },
  { path: 'blog/begrippen/cursus', component: BlogTermComponent, title: 'Wat betekent: Cursus?', data: { slug: 'cursus' } },
  { path: 'blog/begrippen/commissie', component: BlogTermComponent, title: 'Wat betekent: Commissie?', data: { slug: 'commissie' } },
  { path: 'blog/begrippen/dapri', component: BlogTermComponent, title: 'Wat betekent: Dapri?', data: { slug: 'dapri' } },
  { path: 'blog/begrippen/das', component: BlogTermComponent, title: 'Wat betekent: Das?', data: { slug: 'das' } },
  { path: 'blog/begrippen/datediner', component: BlogTermComponent, title: 'Wat betekent: Datediner?', data: { slug: 'datediner' } },
  { path: 'blog/begrippen/dead', component: BlogTermComponent, title: 'Wat betekent: Dead?', data: { slug: 'dead' } },
  { path: 'blog/begrippen/deadline', component: BlogTermComponent, title: 'Wat betekent: Deadline?', data: { slug: 'deadline' } },
  { path: 'blog/begrippen/dealbreaker', component: BlogTermComponent, title: 'Wat betekent: Dealbreaker?', data: { slug: 'dealbreaker' } },
  { path: 'blog/begrippen/deepfake', component: BlogTermComponent, title: 'Wat betekent: Deepfake?', data: { slug: 'deepfake' } },
  { path: 'blog/begrippen/delulu', component: BlogTermComponent, title: 'Wat betekent: Delulu?', data: { slug: 'delulu' } },
  { path: 'blog/begrippen/designated-driver', component: BlogTermComponent, title: 'Wat betekent: Designated driver?', data: { slug: 'designated-driver' } },
  { path: 'blog/begrippen/despo', component: BlogTermComponent, title: 'Wat betekent: Despo?', data: { slug: 'despo' } },
  { path: 'blog/begrippen/deur-verdienen', component: BlogTermComponent, title: 'Wat betekent: Deur verdienen?', data: { slug: 'deur-verdienen' } },
  { path: 'blog/begrippen/dibs', component: BlogTermComponent, title: 'Wat betekent: Dibs?', data: { slug: 'dibs' } },
  { path: 'blog/begrippen/dichtgetikt', component: BlogTermComponent, title: 'Wat betekent: Dichtgetikt?', data: { slug: 'dichtgetikt' } },
  { path: 'blog/begrippen/dies', component: BlogTermComponent, title: 'Wat betekent: Dies?', data: { slug: 'dies' } },
  { path: 'blog/begrippen/digital-footprint', component: BlogTermComponent, title: 'Wat betekent: Digital footprint?', data: { slug: 'digital-footprint' } },
  { path: 'blog/begrippen/dispuut', component: BlogTermComponent, title: 'Wat betekent: Dispuut?', data: { slug: 'dispuut' } },
  { path: 'blog/begrippen/dissertation', component: BlogTermComponent, title: 'Wat betekent: Dissertation?', data: { slug: 'dissertation' } },
  { path: 'blog/begrippen/dive-bar', component: BlogTermComponent, title: 'Wat betekent: Dive bar?', data: { slug: 'dive-bar' } },
  { path: 'blog/begrippen/dm', component: BlogTermComponent, title: 'Wat betekent: DM?', data: { slug: 'dm' } },
  { path: 'blog/begrippen/doomscrolling', component: BlogTermComponent, title: 'Wat betekent: Doomscrolling?', data: { slug: 'doomscrolling' } },
  { path: 'blog/begrippen/doorhalen', component: BlogTermComponent, title: 'Wat betekent: Doorhalen?', data: { slug: 'doorhalen' } },
  { path: 'blog/begrippen/dorm', component: BlogTermComponent, title: 'Wat betekent: Dorm?', data: { slug: 'dorm' } },
  { path: 'blog/begrippen/double-texting', component: BlogTermComponent, title: 'Wat betekent: Double texting?', data: { slug: 'double-texting' } },
  { path: 'blog/begrippen/down-bad', component: BlogTermComponent, title: 'Wat betekent: Down bad?', data: { slug: 'down-bad' } },
  { path: 'blog/begrippen/dragged', component: BlogTermComponent, title: 'Wat betekent: Dragged?', data: { slug: 'dragged' } },
  { path: 'blog/begrippen/driesecondenregel', component: BlogTermComponent, title: 'Wat betekent: Driesecondenregel?', data: { slug: 'driesecondenregel' } },
  { path: 'blog/begrippen/drinking-game', component: BlogTermComponent, title: 'Wat betekent: Drinking game?', data: { slug: 'drinking-game' } },
  { path: 'blog/begrippen/drip', component: BlogTermComponent, title: 'Wat betekent: Drip?', data: { slug: 'drip' } },
  { path: 'blog/begrippen/dropout', component: BlogTermComponent, title: 'Wat betekent: Dropout?', data: { slug: 'dropout' } },
  { path: 'blog/begrippen/dry-texting', component: BlogTermComponent, title: 'Wat betekent: Dry texting?', data: { slug: 'dry-texting' } },
  { path: 'blog/begrippen/dtr', component: BlogTermComponent, title: 'Wat betekent: DTR?', data: { slug: 'dtr' } },
  { path: 'blog/begrippen/dubbel-gemengd', component: BlogTermComponent, title: 'Wat betekent: Dubbel gemengd?', data: { slug: 'dubbel-gemengd' } },
  { path: 'blog/begrippen/duet', component: BlogTermComponent, title: 'Wat betekent: Duet?', data: { slug: 'duet' } },
  { path: 'blog/begrippen/duft', component: BlogTermComponent, title: 'Wat betekent: Duft?', data: { slug: 'duft' } },
  { path: 'blog/begrippen/duo', component: BlogTermComponent, title: 'Wat betekent: DUO?', data: { slug: 'duo' } },
  { path: 'blog/begrippen/droog-staan', component: BlogTermComponent, title: 'Wat betekent: Droog staan?', data: { slug: 'droog-staan' } },
  { path: 'blog/begrippen/el-cid', component: BlogTermComponent, title: 'Wat betekent: EL CID?', data: { slug: 'el-cid' } },
  { path: 'blog/begrippen/elective', component: BlogTermComponent, title: 'Wat betekent: Elective?', data: { slug: 'elective' } },
  { path: 'blog/begrippen/engagement-bait', component: BlogTermComponent, title: 'Wat betekent: Engagement bait?', data: { slug: 'engagement-bait' } },
  { path: 'blog/begrippen/era', component: BlogTermComponent, title: 'Wat betekent: Era?', data: { slug: 'era' } },
  { path: 'blog/begrippen/esca', component: BlogTermComponent, title: 'Wat betekent: Esca?', data: { slug: 'esca' } },
  { path: 'blog/begrippen/escaleren', component: BlogTermComponent, title: 'Wat betekent: Escaleren?', data: { slug: 'escaleren' } },
  { path: 'blog/begrippen/esma', component: BlogTermComponent, title: 'Wat betekent: Esma?', data: { slug: 'esma' } },
  { path: 'blog/begrippen/eventuela', component: BlogTermComponent, title: 'Wat betekent: Eventuela?', data: { slug: 'eventuela' } },
  { path: 'blog/begrippen/exchange-student', component: BlogTermComponent, title: 'Wat betekent: Exchange student?', data: { slug: 'exchange-student' } },
  { path: 'blog/begrippen/exclu', component: BlogTermComponent, title: 'Wat betekent: Exclu?', data: { slug: 'exclu' } },
  { path: 'blog/begrippen/exclusief', component: BlogTermComponent, title: 'Wat betekent: Exclusief?', data: { slug: 'exclusief' } },
  { path: 'blog/begrippen/extern', component: BlogTermComponent, title: 'Wat betekent: Extern?', data: { slug: 'extern' } },
  { path: 'blog/begrippen/facetune', component: BlogTermComponent, title: 'Wat betekent: FaceTune?', data: { slug: 'facetune' } },
  { path: 'blog/begrippen/facts', component: BlogTermComponent, title: 'Wat betekent: Facts?', data: { slug: 'facts' } },
  { path: 'blog/begrippen/feut', component: BlogTermComponent, title: 'Wat betekent: Feut?', data: { slug: 'feut' } },
  { path: 'blog/begrippen/filter', component: BlogTermComponent, title: 'Wat betekent: Filter?', data: { slug: 'filter' } },
  { path: 'blog/begrippen/finsta', component: BlogTermComponent, title: 'Wat betekent: FinSta?', data: { slug: 'finsta' } },
  { path: 'blog/begrippen/fire', component: BlogTermComponent, title: 'Wat betekent: Fire?', data: { slug: 'fire' } },
  { path: 'blog/begrippen/fit-check', component: BlogTermComponent, title: 'Wat betekent: Fit check?', data: { slug: 'fit-check' } },
  { path: 'blog/begrippen/flaneren', component: BlogTermComponent, title: 'Wat betekent: Flaneren?', data: { slug: 'flaneren' } },
  { path: 'blog/begrippen/flatmate', component: BlogTermComponent, title: 'Wat betekent: Flatmate?', data: { slug: 'flatmate' } },
  { path: 'blog/begrippen/flex', component: BlogTermComponent, title: 'Wat betekent: Flex?', data: { slug: 'flex' } },
  { path: 'blog/begrippen/flip-cup', component: BlogTermComponent, title: 'Wat betekent: Flip cup?', data: { slug: 'flip-cup' } },
  { path: 'blog/begrippen/fml', component: BlogTermComponent, title: 'Wat betekent: FML?', data: { slug: 'fml' } },
  { path: 'blog/begrippen/fomo', component: BlogTermComponent, title: 'Wat betekent: FOMO?', data: { slug: 'fomo' } },
  { path: 'blog/begrippen/frat', component: BlogTermComponent, title: 'Wat betekent: Frat?', data: { slug: 'frat' } },
  { path: 'blog/begrippen/frat-party', component: BlogTermComponent, title: 'Wat betekent: Frat party?', data: { slug: 'frat-party' } },
  { path: 'blog/begrippen/fresher', component: BlogTermComponent, title: 'Wat betekent: Fresher?', data: { slug: 'fresher' } },
  { path: 'blog/begrippen/freshers-week', component: BlogTermComponent, title: 'Wat betekent: Freshers\' Week?', data: { slug: 'freshers-week' } },
  { path: 'blog/begrippen/freshman', component: BlogTermComponent, title: 'Wat betekent: Freshman?', data: { slug: 'freshman' } },
  { path: 'blog/begrippen/friendzone', component: BlogTermComponent, title: 'Wat betekent: Friendzone?', data: { slug: 'friendzone' } },
  { path: 'blog/begrippen/fuif', component: BlogTermComponent, title: 'Wat betekent: Fuif?', data: { slug: 'fuif' } },
  { path: 'blog/begrippen/fusie', component: BlogTermComponent, title: 'Wat betekent: Fusie?', data: { slug: 'fusie' } },
  { path: 'blog/begrippen/fwb', component: BlogTermComponent, title: 'Wat betekent: FWB?', data: { slug: 'fwb' } },
  { path: 'blog/begrippen/fyi', component: BlogTermComponent, title: 'Wat betekent: FYI?', data: { slug: 'fyi' } },
  { path: 'blog/begrippen/fyp', component: BlogTermComponent, title: 'Wat betekent: FYP?', data: { slug: 'fyp' } },
  { path: 'blog/begrippen/galaplicht', component: BlogTermComponent, title: 'Wat betekent: Galaplicht?', data: { slug: 'galaplicht' } },
  { path: 'blog/begrippen/gap-year', component: BlogTermComponent, title: 'Wat betekent: Gap year?', data: { slug: 'gap-year' } },
  { path: 'blog/begrippen/gaslighting', component: BlogTermComponent, title: 'Wat betekent: Gaslighting?', data: { slug: 'gaslighting' } },
  { path: 'blog/begrippen/gefeli', component: BlogTermComponent, title: 'Wat betekent: Gefeli?', data: { slug: 'gefeli' } },
  { path: 'blog/begrippen/geru', component: BlogTermComponent, title: 'Wat betekent: Geru?', data: { slug: 'geru' } },
  { path: 'blog/begrippen/gezel', component: BlogTermComponent, title: 'Wat betekent: Gezel?', data: { slug: 'gezel' } },
  { path: 'blog/begrippen/ghost-account', component: BlogTermComponent, title: 'Wat betekent: Ghost account?', data: { slug: 'ghost-account' } },
  { path: 'blog/begrippen/ghosting', component: BlogTermComponent, title: 'Wat betekent: Ghosting?', data: { slug: 'ghosting' } },
  { path: 'blog/begrippen/ginto', component: BlogTermComponent, title: 'Wat betekent: GinTo?', data: { slug: 'ginto' } },
  { path: 'blog/begrippen/gk', component: BlogTermComponent, title: 'Wat betekent: GK?', data: { slug: 'gk' } },
  { path: 'blog/begrippen/glazing', component: BlogTermComponent, title: 'Wat betekent: Glazing?', data: { slug: 'glazing' } },
  { path: 'blog/begrippen/glow-up', component: BlogTermComponent, title: 'Wat betekent: Glow-up?', data: { slug: 'glow-up' } },
  { path: 'blog/begrippen/goat', component: BlogTermComponent, title: 'Wat betekent: GOAT?', data: { slug: 'goat' } },
  { path: 'blog/begrippen/goos', component: BlogTermComponent, title: 'Wat betekent: Goos?', data: { slug: 'goos' } },
  { path: 'blog/begrippen/gozer', component: BlogTermComponent, title: 'Wat betekent: Gozer?', data: { slug: 'gozer' } },
  { path: 'blog/begrippen/gpa', component: BlogTermComponent, title: 'Wat betekent: GPA?', data: { slug: 'gpa' } },
  { path: 'blog/begrippen/gr', component: BlogTermComponent, title: 'Wat betekent: GR?', data: { slug: 'gr' } },
  { path: 'blog/begrippen/green-flag', component: BlogTermComponent, title: 'Wat betekent: Green flag?', data: { slug: 'green-flag' } },
  { path: 'blog/begrippen/grondpannenkoek', component: BlogTermComponent, title: 'Wat betekent: Grondpannenkoek?', data: { slug: 'grondpannenkoek' } },
  { path: 'blog/begrippen/grondpizza', component: BlogTermComponent, title: 'Wat betekent: Grondpizza?', data: { slug: 'grondpizza' } },
  { path: 'blog/begrippen/group-project', component: BlogTermComponent, title: 'Wat betekent: Group project?', data: { slug: 'group-project' } },
  { path: 'blog/begrippen/grwm', component: BlogTermComponent, title: 'Wat betekent: GRWM?', data: { slug: 'grwm' } },
  { path: 'blog/begrippen/guac', component: BlogTermComponent, title: 'Wat betekent: Guac?', data: { slug: 'guac' } },
  { path: 'blog/begrippen/guest-list', component: BlogTermComponent, title: 'Wat betekent: Guest list?', data: { slug: 'guest-list' } },
  { path: 'blog/begrippen/guilty-pleasure', component: BlogTermComponent, title: 'Wat betekent: Guilty pleasure?', data: { slug: 'guilty-pleasure' } },
  { path: 'blog/begrippen/haasje', component: BlogTermComponent, title: 'Wat betekent: Haasje?', data: { slug: 'haasje' } },
  { path: 'blog/begrippen/hair-of-the-dog', component: BlogTermComponent, title: 'Wat betekent: Hair of the dog?', data: { slug: 'hair-of-the-dog' } },
  { path: 'blog/begrippen/halve-leo', component: BlogTermComponent, title: 'Wat betekent: Halve leo?', data: { slug: 'halve-leo' } },
  { path: 'blog/begrippen/hangover', component: BlogTermComponent, title: 'Wat betekent: Hangover?', data: { slug: 'hangover' } },
  { path: 'blog/begrippen/happy-hour', component: BlogTermComponent, title: 'Wat betekent: Happy hour?', data: { slug: 'happy-hour' } },
  { path: 'blog/begrippen/hard-launch', component: BlogTermComponent, title: 'Wat betekent: Hard launch?', data: { slug: 'hard-launch' } },
  { path: 'blog/begrippen/hater', component: BlogTermComponent, title: 'Wat betekent: Hater?', data: { slug: 'hater' } },
  { path: 'blog/begrippen/heavyweight', component: BlogTermComponent, title: 'Wat betekent: Heavyweight?', data: { slug: 'heavyweight' } },
  { path: 'blog/begrippen/her', component: BlogTermComponent, title: 'Wat betekent: Her?', data: { slug: 'her' } },
  { path: 'blog/begrippen/hertje', component: BlogTermComponent, title: 'Wat betekent: Hertje?', data: { slug: 'hertje' } },
  { path: 'blog/begrippen/hg', component: BlogTermComponent, title: 'Wat betekent: HG?', data: { slug: 'hg' } },
  { path: 'blog/begrippen/highkey', component: BlogTermComponent, title: 'Wat betekent: Highkey?', data: { slug: 'highkey' } },
  { path: 'blog/begrippen/hila', component: BlogTermComponent, title: 'Wat betekent: Hila?', data: { slug: 'hila' } },
  { path: 'blog/begrippen/hj', component: BlogTermComponent, title: 'Wat betekent: HJ?', data: { slug: 'hj' } },
  { path: 'blog/begrippen/honk', component: BlogTermComponent, title: 'Wat betekent: Honk?', data: { slug: 'honk' } },
  { path: 'blog/begrippen/hookup', component: BlogTermComponent, title: 'Wat betekent: Hookup?', data: { slug: 'hookup' } },
  { path: 'blog/begrippen/hospi', component: BlogTermComponent, title: 'Wat betekent: Hospi?', data: { slug: 'hospi' } },
  { path: 'blog/begrippen/hospiteren', component: BlogTermComponent, title: 'Wat betekent: Hospiteren?', data: { slug: 'hospiteren' } },
  { path: 'blog/begrippen/hot-take', component: BlogTermComponent, title: 'Wat betekent: Hot take?', data: { slug: 'hot-take' } },
  { path: 'blog/begrippen/houdini', component: BlogTermComponent, title: 'Wat betekent: Houdini?', data: { slug: 'houdini' } },
  { path: 'blog/begrippen/house-party', component: BlogTermComponent, title: 'Wat betekent: House party?', data: { slug: 'house-party' } },
  { path: 'blog/begrippen/huig-hockeyen', component: BlogTermComponent, title: 'Wat betekent: Huig hockeyen?', data: { slug: 'huig-hockeyen' } },
  { path: 'blog/begrippen/huisjongste', component: BlogTermComponent, title: 'Wat betekent: Huisjongste?', data: { slug: 'huisjongste' } },
  { path: 'blog/begrippen/huispanda', component: BlogTermComponent, title: 'Wat betekent: Huispanda?', data: { slug: 'huispanda' } },
  { path: 'blog/begrippen/huisparasiet', component: BlogTermComponent, title: 'Wat betekent: Huisparasiet?', data: { slug: 'huisparasiet' } },
  { path: 'blog/begrippen/hustle-culture', component: BlogTermComponent, title: 'Wat betekent: Hustle culture?', data: { slug: 'hustle-culture' } },
  { path: 'blog/begrippen/hv', component: BlogTermComponent, title: 'Wat betekent: HV?', data: { slug: 'hv' } },
  { path: 'blog/begrippen/herstelbiertje', component: BlogTermComponent, title: 'Wat betekent: Herstelbiertje?', data: { slug: 'herstelbiertje' } },
  { path: 'blog/begrippen/ibu', component: BlogTermComponent, title: 'Wat betekent: Ibu?', data: { slug: 'ibu' } },
  { path: 'blog/begrippen/icen', component: BlogTermComponent, title: 'Wat betekent: Icen?', data: { slug: 'icen' } },
  { path: 'blog/begrippen/ick', component: BlogTermComponent, title: 'Wat betekent: Ick?', data: { slug: 'ick' } },
  { path: 'blog/begrippen/idc', component: BlogTermComponent, title: 'Wat betekent: IDC?', data: { slug: 'idc' } },
  { path: 'blog/begrippen/idk', component: BlogTermComponent, title: 'Wat betekent: IDK?', data: { slug: 'idk' } },
  { path: 'blog/begrippen/ijskast', component: BlogTermComponent, title: 'Wat betekent: IJskast?', data: { slug: 'ijskast' } },
  { path: 'blog/begrippen/im-weak', component: BlogTermComponent, title: 'Wat betekent: I\'m weak?', data: { slug: 'im-weak' } },
  { path: 'blog/begrippen/imo', component: BlogTermComponent, title: 'Wat betekent: IMO?', data: { slug: 'imo' } },
  { path: 'blog/begrippen/imposter-syndrome', component: BlogTermComponent, title: 'Wat betekent: Imposter syndrome?', data: { slug: 'imposter-syndrome' } },
  { path: 'blog/begrippen/in-my-era', component: BlogTermComponent, title: 'Wat betekent: In my ___ era?', data: { slug: 'in-my-era' } },
  { path: 'blog/begrippen/inauguratie', component: BlogTermComponent, title: 'Wat betekent: Inauguratie?', data: { slug: 'inauguratie' } },
  { path: 'blog/begrippen/indikken', component: BlogTermComponent, title: 'Wat betekent: Indikken?', data: { slug: 'indikken' } },
  { path: 'blog/begrippen/indrinken', component: BlogTermComponent, title: 'Wat betekent: Indrinken?', data: { slug: 'indrinken' } },
  { path: 'blog/begrippen/influ', component: BlogTermComponent, title: 'Wat betekent: Influ?', data: { slug: 'influ' } },
  { path: 'blog/begrippen/inkakken', component: BlogTermComponent, title: 'Wat betekent: Inkakken?', data: { slug: 'inkakken' } },
  { path: 'blog/begrippen/instemmen', component: BlogTermComponent, title: 'Wat betekent: Instemmen?', data: { slug: 'instemmen' } },
  { path: 'blog/begrippen/internacho', component: BlogTermComponent, title: 'Wat betekent: Internacho?', data: { slug: 'internacho' } },
  { path: 'blog/begrippen/internet-personality', component: BlogTermComponent, title: 'Wat betekent: Internet personality?', data: { slug: 'internet-personality' } },
  { path: 'blog/begrippen/internship', component: BlogTermComponent, title: 'Wat betekent: Internship?', data: { slug: 'internship' } },
  { path: 'blog/begrippen/introductieweek', component: BlogTermComponent, title: 'Wat betekent: Introductieweek?', data: { slug: 'introductieweek' } },
  { path: 'blog/begrippen/irl', component: BlogTermComponent, title: 'Wat betekent: IRL?', data: { slug: 'irl' } },
  { path: 'blog/begrippen/italiaans-afscheid', component: BlogTermComponent, title: 'Wat betekent: Italiaans afscheid?', data: { slug: 'italiaans-afscheid' } },
  { path: 'blog/begrippen/its-giving', component: BlogTermComponent, title: 'Wat betekent: It\'s giving?', data: { slug: 'its-giving' } },
  { path: 'blog/begrippen/iykyk', component: BlogTermComponent, title: 'Wat betekent: IYKYK?', data: { slug: 'iykyk' } },
  { path: 'blog/begrippen/jaarclub', component: BlogTermComponent, title: 'Wat betekent: Jaarclub?', data: { slug: 'jaarclub' } },
  { path: 'blog/begrippen/jasje-dasje', component: BlogTermComponent, title: 'Wat betekent: Jasje dasje?', data: { slug: 'jasje-dasje' } },
  { path: 'blog/begrippen/jc', component: BlogTermComponent, title: 'Wat betekent: JC?', data: { slug: 'jc' } },
  { path: 'blog/begrippen/jagerbomb', component: BlogTermComponent, title: 'Wat betekent: Jägerbomb?', data: { slug: 'jagerbomb' } },
  { path: 'blog/begrippen/jomo', component: BlogTermComponent, title: 'Wat betekent: JOMO?', data: { slug: 'jomo' } },
  { path: 'blog/begrippen/junior', component: BlogTermComponent, title: 'Wat betekent: Junior?', data: { slug: 'junior' } },
  { path: 'blog/begrippen/kaasschaaf', component: BlogTermComponent, title: 'Wat betekent: Kaasschaaf?', data: { slug: 'kaasschaaf' } },
  { path: 'blog/begrippen/kantelen', component: BlogTermComponent, title: 'Wat betekent: Kantelen?', data: { slug: 'kantelen' } },
  { path: 'blog/begrippen/kapstokhertje', component: BlogTermComponent, title: 'Wat betekent: Kapstokhertje?', data: { slug: 'kapstokhertje' } },
  { path: 'blog/begrippen/kater', component: BlogTermComponent, title: 'Wat betekent: Kater?', data: { slug: 'kater' } },
  { path: 'blog/begrippen/kings-cup', component: BlogTermComponent, title: 'Wat betekent: Kings Cup?', data: { slug: 'kings-cup' } },
  { path: 'blog/begrippen/kmt', component: BlogTermComponent, title: 'Wat betekent: KMT?', data: { slug: 'kmt' } },
  { path: 'blog/begrippen/knor', component: BlogTermComponent, title: 'Wat betekent: Knor?', data: { slug: 'knor' } },
  { path: 'blog/begrippen/kompaan', component: BlogTermComponent, title: 'Wat betekent: Kompaan?', data: { slug: 'kompaan' } },
  { path: 'blog/begrippen/kot', component: BlogTermComponent, title: 'Wat betekent: Kot?', data: { slug: 'kot' } },
  { path: 'blog/begrippen/krokant', component: BlogTermComponent, title: 'Wat betekent: Krokant?', data: { slug: 'krokant' } },
  { path: 'blog/begrippen/kruipafstand', component: BlogTermComponent, title: 'Wat betekent: Kruipafstand?', data: { slug: 'kruipafstand' } },
  { path: 'blog/begrippen/kwarrel', component: BlogTermComponent, title: 'Wat betekent: Kwarrel?', data: { slug: 'kwarrel' } },
  { path: 'blog/begrippen/l', component: BlogTermComponent, title: 'Wat betekent: L?', data: { slug: 'l' } },
  { path: 'blog/begrippen/labo', component: BlogTermComponent, title: 'Wat betekent: Labo?', data: { slug: 'labo' } },
  { path: 'blog/begrippen/last-call', component: BlogTermComponent, title: 'Wat betekent: Last call?', data: { slug: 'last-call' } },
  { path: 'blog/begrippen/lecture', component: BlogTermComponent, title: 'Wat betekent: Lecture?', data: { slug: 'lecture' } },
  { path: 'blog/begrippen/leenstelsel', component: BlogTermComponent, title: 'Wat betekent: Leenstelsel?', data: { slug: 'leenstelsel' } },
  { path: 'blog/begrippen/left-on-delivered', component: BlogTermComponent, title: 'Wat betekent: Left on delivered?', data: { slug: 'left-on-delivered' } },
  { path: 'blog/begrippen/left-on-read', component: BlogTermComponent, title: 'Wat betekent: Left on read?', data: { slug: 'left-on-read' } },
  { path: 'blog/begrippen/let-him-cook', component: BlogTermComponent, title: 'Wat betekent: Let him cook?', data: { slug: 'let-him-cook' } },
  { path: 'blog/begrippen/level-up', component: BlogTermComponent, title: 'Wat betekent: Level up?', data: { slug: 'level-up' } },
  { path: 'blog/begrippen/life-hack', component: BlogTermComponent, title: 'Wat betekent: Life hack?', data: { slug: 'life-hack' } },
  { path: 'blog/begrippen/lightweight', component: BlogTermComponent, title: 'Wat betekent: Lightweight?', data: { slug: 'lightweight' } },
  { path: 'blog/begrippen/lit', component: BlogTermComponent, title: 'Wat betekent: Lit?', data: { slug: 'lit' } },
  { path: 'blog/begrippen/living-my-best-life', component: BlogTermComponent, title: 'Wat betekent: Living my best life?', data: { slug: 'living-my-best-life' } },
  { path: 'blog/begrippen/lmao', component: BlogTermComponent, title: 'Wat betekent: LMAO?', data: { slug: 'lmao' } },
  { path: 'blog/begrippen/lmk', component: BlogTermComponent, title: 'Wat betekent: LMK?', data: { slug: 'lmk' } },
  { path: 'blog/begrippen/loca', component: BlogTermComponent, title: 'Wat betekent: Loca?', data: { slug: 'loca' } },
  { path: 'blog/begrippen/locked-in', component: BlogTermComponent, title: 'Wat betekent: Locked in?', data: { slug: 'locked-in' } },
  { path: 'blog/begrippen/lol', component: BlogTermComponent, title: 'Wat betekent: LOL?', data: { slug: 'lol' } },
  { path: 'blog/begrippen/lore', component: BlogTermComponent, title: 'Wat betekent: Lore?', data: { slug: 'lore' } },
  { path: 'blog/begrippen/louter', component: BlogTermComponent, title: 'Wat betekent: Louter?', data: { slug: 'louter' } },
  { path: 'blog/begrippen/love-bombing', component: BlogTermComponent, title: 'Wat betekent: Love bombing?', data: { slug: 'love-bombing' } },
  { path: 'blog/begrippen/lowkey', component: BlogTermComponent, title: 'Wat betekent: Lowkey?', data: { slug: 'lowkey' } },
  { path: 'blog/begrippen/ludiek', component: BlogTermComponent, title: 'Wat betekent: Ludiek?', data: { slug: 'ludiek' } },
  { path: 'blog/begrippen/lullepot', component: BlogTermComponent, title: 'Wat betekent: Lullepot?', data: { slug: 'lullepot' } },
  { path: 'blog/begrippen/lurking', component: BlogTermComponent, title: 'Wat betekent: Lurking?', data: { slug: 'lurking' } },
  { path: 'blog/begrippen/lustrum', component: BlogTermComponent, title: 'Wat betekent: Lustrum?', data: { slug: 'lustrum' } },
  { path: 'blog/begrippen/lapswans', component: BlogTermComponent, title: 'Wat betekent: Lapswans?', data: { slug: 'lapswans' } },
  { path: 'blog/begrippen/m', component: BlogTermComponent, title: 'Wat betekent: M?', data: { slug: 'm' } },
  { path: 'blog/begrippen/maat', component: BlogTermComponent, title: 'Wat betekent: Maat?', data: { slug: 'maat' } },
  { path: 'blog/begrippen/main-character', component: BlogTermComponent, title: 'Wat betekent: Main character?', data: { slug: 'main-character' } },
  { path: 'blog/begrippen/major', component: BlogTermComponent, title: 'Wat betekent: Major?', data: { slug: 'major' } },
  { path: 'blog/begrippen/matras', component: BlogTermComponent, title: 'Wat betekent: Matras?', data: { slug: 'matras' } },
  { path: 'blog/begrippen/mc', component: BlogTermComponent, title: 'Wat betekent: MC?', data: { slug: 'mc' } },
  { path: 'blog/begrippen/mdm', component: BlogTermComponent, title: 'Wat betekent: MDM?', data: { slug: 'mdm' } },
  { path: 'blog/begrippen/medium', component: BlogTermComponent, title: 'Wat betekent: Medium?', data: { slug: 'medium' } },
  { path: 'blog/begrippen/meme', component: BlogTermComponent, title: 'Wat betekent: Meme?', data: { slug: 'meme' } },
  { path: 'blog/begrippen/meter-bier', component: BlogTermComponent, title: 'Wat betekent: Meter?', data: { slug: 'meter-bier' } },
  { path: 'blog/begrippen/micro-cheating', component: BlogTermComponent, title: 'Wat betekent: Micro-cheating?', data: { slug: 'micro-cheating' } },
  { path: 'blog/begrippen/mid', component: BlogTermComponent, title: 'Wat betekent: Mid?', data: { slug: 'mid' } },
  { path: 'blog/begrippen/miemelen', component: BlogTermComponent, title: 'Wat betekent: Miemelen?', data: { slug: 'miemelen' } },
  { path: 'blog/begrippen/minor', component: BlogTermComponent, title: 'Wat betekent: Minor?', data: { slug: 'minor' } },
  { path: 'blog/begrippen/mood', component: BlogTermComponent, title: 'Wat betekent: Mood?', data: { slug: 'mood' } },
  { path: 'blog/begrippen/mores', component: BlogTermComponent, title: 'Wat betekent: Mores?', data: { slug: 'mores' } },
  { path: 'blog/begrippen/mattie', component: BlogTermComponent, title: 'Wat betekent: Mattie?', data: { slug: 'mattie' } },
  { path: 'blog/begrippen/nakkie', component: BlogTermComponent, title: 'Wat betekent: Nakkie?', data: { slug: 'nakkie' } },
  { path: 'blog/begrippen/ngl', component: BlogTermComponent, title: 'Wat betekent: NGL?', data: { slug: 'ngl' } },
  { path: 'blog/begrippen/night-out', component: BlogTermComponent, title: 'Wat betekent: Night out?', data: { slug: 'night-out' } },
  { path: 'blog/begrippen/nominaal-lopen', component: BlogTermComponent, title: 'Wat betekent: Nominaal lopen?', data: { slug: 'nominaal-lopen' } },
  { path: 'blog/begrippen/normi', component: BlogTermComponent, title: 'Wat betekent: Normi?', data: { slug: 'normi' } },
  { path: 'blog/begrippen/npc', component: BlogTermComponent, title: 'Wat betekent: NPC?', data: { slug: 'npc' } },
  { path: 'blog/begrippen/nul', component: BlogTermComponent, title: 'Wat betekent: Nul?', data: { slug: 'nul' } },
  { path: 'blog/begrippen/nekken', component: BlogTermComponent, title: 'Wat betekent: Nekken?', data: { slug: 'nekken' } },
  { path: 'blog/begrippen/office-hours', component: BlogTermComponent, title: 'Wat betekent: Office hours?', data: { slug: 'office-hours' } },
  { path: 'blog/begrippen/omw', component: BlogTermComponent, title: 'Wat betekent: OMW?', data: { slug: 'omw' } },
  { path: 'blog/begrippen/one-night-stand', component: BlogTermComponent, title: 'Wat betekent: One-night stand?', data: { slug: 'one-night-stand' } },
  { path: 'blog/begrippen/ontgroening', component: BlogTermComponent, title: 'Wat betekent: Ontgroening?', data: { slug: 'ontgroening' } },
  { path: 'blog/begrippen/ootd', component: BlogTermComponent, title: 'Wat betekent: OOTD?', data: { slug: 'ootd' } },
  { path: 'blog/begrippen/orbiting', component: BlogTermComponent, title: 'Wat betekent: Orbiting?', data: { slug: 'orbiting' } },
  { path: 'blog/begrippen/out-of-pocket', component: BlogTermComponent, title: 'Wat betekent: Out of pocket?', data: { slug: 'out-of-pocket' } },
  { path: 'blog/begrippen/p', component: BlogTermComponent, title: 'Wat betekent: P?', data: { slug: 'p' } },
  { path: 'blog/begrippen/pabo', component: BlogTermComponent, title: 'Wat betekent: Pabo?', data: { slug: 'pabo' } },
  { path: 'blog/begrippen/paklijst', component: BlogTermComponent, title: 'Wat betekent: Paklijst?', data: { slug: 'paklijst' } },
  { path: 'blog/begrippen/pandapunten', component: BlogTermComponent, title: 'Wat betekent: Pandapunten?', data: { slug: 'pandapunten' } },
  { path: 'blog/begrippen/para', component: BlogTermComponent, title: 'Wat betekent: Para?', data: { slug: 'para' } },
  { path: 'blog/begrippen/parasocial-relationship', component: BlogTermComponent, title: 'Wat betekent: Parasocial relationship?', data: { slug: 'parasocial-relationship' } },
  { path: 'blog/begrippen/party-animal', component: BlogTermComponent, title: 'Wat betekent: Party animal?', data: { slug: 'party-animal' } },
  { path: 'blog/begrippen/pauper', component: BlogTermComponent, title: 'Wat betekent: Pauper?', data: { slug: 'pauper' } },
  { path: 'blog/begrippen/pechgeneratie', component: BlogTermComponent, title: 'Wat betekent: Pechgeneratie?', data: { slug: 'pechgeneratie' } },
  { path: 'blog/begrippen/period', component: BlogTermComponent, title: 'Wat betekent: Period?', data: { slug: 'period' } },
  { path: 'blog/begrippen/photo-dump', component: BlogTermComponent, title: 'Wat betekent: Photo dump?', data: { slug: 'photo-dump' } },
  { path: 'blog/begrippen/pick-me', component: BlogTermComponent, title: 'Wat betekent: Pick-me?', data: { slug: 'pick-me' } },
  { path: 'blog/begrippen/pint', component: BlogTermComponent, title: 'Wat betekent: Pint?', data: { slug: 'pint' } },
  { path: 'blog/begrippen/pinten-harken', component: BlogTermComponent, title: 'Wat betekent: Pinten harken?', data: { slug: 'pinten-harken' } },
  { path: 'blog/begrippen/plafonddienst', component: BlogTermComponent, title: 'Wat betekent: Plafonddienst?', data: { slug: 'plafonddienst' } },
  { path: 'blog/begrippen/plot-twist', component: BlogTermComponent, title: 'Wat betekent: Plot twist?', data: { slug: 'plot-twist' } },
  { path: 'blog/begrippen/pocketing', component: BlogTermComponent, title: 'Wat betekent: Pocketing?', data: { slug: 'pocketing' } },
  { path: 'blog/begrippen/pov', component: BlogTermComponent, title: 'Wat betekent: POV?', data: { slug: 'pov' } },
  { path: 'blog/begrippen/praeses', component: BlogTermComponent, title: 'Wat betekent: Praeses?', data: { slug: 'praeses' } },
  { path: 'blog/begrippen/pre-drinks', component: BlogTermComponent, title: 'Wat betekent: Pre-drinks?', data: { slug: 'pre-drinks' } },
  { path: 'blog/begrippen/prela', component: BlogTermComponent, title: 'Wat betekent: Prela?', data: { slug: 'prela' } },
  { path: 'blog/begrippen/pro-tip', component: BlogTermComponent, title: 'Wat betekent: Pro tip?', data: { slug: 'pro-tip' } },
  { path: 'blog/begrippen/proleet', component: BlogTermComponent, title: 'Wat betekent: Proleet?', data: { slug: 'proleet' } },
  { path: 'blog/begrippen/promi', component: BlogTermComponent, title: 'Wat betekent: Promi?', data: { slug: 'promi' } },
  { path: 'blog/begrippen/prominent', component: BlogTermComponent, title: 'Wat betekent: Prominent?', data: { slug: 'prominent' } },
  { path: 'blog/begrippen/propedeuse', component: BlogTermComponent, title: 'Wat betekent: Propedeuse?', data: { slug: 'propedeuse' } },
  { path: 'blog/begrippen/pub', component: BlogTermComponent, title: 'Wat betekent: Pub?', data: { slug: 'pub' } },
  { path: 'blog/begrippen/pub-crawl', component: BlogTermComponent, title: 'Wat betekent: Pub crawl?', data: { slug: 'pub-crawl' } },
  { path: 'blog/begrippen/quaestor-quaestrix', component: BlogTermComponent, title: 'Wat betekent: Quaestor / Quaestrix?', data: { slug: 'quaestor-quaestrix' } },
  { path: 'blog/begrippen/quarter-life-crisis', component: BlogTermComponent, title: 'Wat betekent: Quarter-life crisis?', data: { slug: 'quarter-life-crisis' } },
  { path: 'blog/begrippen/queue', component: BlogTermComponent, title: 'Wat betekent: Queue?', data: { slug: 'queue' } },
  { path: 'blog/begrippen/rage-bait', component: BlogTermComponent, title: 'Wat betekent: Rage-bait?', data: { slug: 'rage-bait' } },
  { path: 'blog/begrippen/ratio', component: BlogTermComponent, title: 'Wat betekent: Ratio?', data: { slug: 'ratio' } },
  { path: 'blog/begrippen/rattentaxi', component: BlogTermComponent, title: 'Wat betekent: Rattentaxi?', data: { slug: 'rattentaxi' } },
  { path: 'blog/begrippen/reaction-video', component: BlogTermComponent, title: 'Wat betekent: Reaction video?', data: { slug: 'reaction-video' } },
  { path: 'blog/begrippen/real', component: BlogTermComponent, title: 'Wat betekent: Real?', data: { slug: 'real' } },
  { path: 'blog/begrippen/rebound', component: BlogTermComponent, title: 'Wat betekent: Rebound?', data: { slug: 'rebound' } },
  { path: 'blog/begrippen/receipts', component: BlogTermComponent, title: 'Wat betekent: Receipts?', data: { slug: 'receipts' } },
  { path: 'blog/begrippen/red-flag', component: BlogTermComponent, title: 'Wat betekent: Red flag?', data: { slug: 'red-flag' } },
  { path: 'blog/begrippen/regelen', component: BlogTermComponent, title: 'Wat betekent: Regelen?', data: { slug: 'regelen' } },
  { path: 'blog/begrippen/regenjas', component: BlogTermComponent, title: 'Wat betekent: Regenjas?', data: { slug: 'regenjas' } },
  { path: 'blog/begrippen/rela', component: BlogTermComponent, title: 'Wat betekent: Rela?', data: { slug: 'rela' } },
  { path: 'blog/begrippen/relationship-goals', component: BlogTermComponent, title: 'Wat betekent: Relationship goals?', data: { slug: 'relationship-goals' } },
  { path: 'blog/begrippen/rent-free', component: BlogTermComponent, title: 'Wat betekent: Rent free?', data: { slug: 'rent-free' } },
  { path: 'blog/begrippen/reparadler', component: BlogTermComponent, title: 'Wat betekent: Reparadler?', data: { slug: 'reparadler' } },
  { path: 'blog/begrippen/reunist', component: BlogTermComponent, title: 'Wat betekent: Reünist?', data: { slug: 'reunist' } },
  { path: 'blog/begrippen/riet', component: BlogTermComponent, title: 'Wat betekent: Riet?', data: { slug: 'riet' } },
  { path: 'blog/begrippen/rietadt', component: BlogTermComponent, title: 'Wat betekent: Rietadt?', data: { slug: 'rietadt' } },
  { path: 'blog/begrippen/rietbak', component: BlogTermComponent, title: 'Wat betekent: Rietbak?', data: { slug: 'rietbak' } },
  { path: 'blog/begrippen/rip', component: BlogTermComponent, title: 'Wat betekent: RIP?', data: { slug: 'rip' } },
  { path: 'blog/begrippen/rizz', component: BlogTermComponent, title: 'Wat betekent: Rizz?', data: { slug: 'rizz' } },
  { path: 'blog/begrippen/rn', component: BlogTermComponent, title: 'Wat betekent: RN?', data: { slug: 'rn' } },
  { path: 'blog/begrippen/roasted', component: BlogTermComponent, title: 'Wat betekent: Roasted?', data: { slug: 'roasted' } },
  { path: 'blog/begrippen/rofl', component: BlogTermComponent, title: 'Wat betekent: ROFL?', data: { slug: 'rofl' } },
  { path: 'blog/begrippen/roommate', component: BlogTermComponent, title: 'Wat betekent: Roommate?', data: { slug: 'roommate' } },
  { path: 'blog/begrippen/safedate', component: BlogTermComponent, title: 'Wat betekent: Safedate?', data: { slug: 'safedate' } },
  { path: 'blog/begrippen/salty', component: BlogTermComponent, title: 'Wat betekent: Salty?', data: { slug: 'salty' } },
  { path: 'blog/begrippen/savage', component: BlogTermComponent, title: 'Wat betekent: Savage?', data: { slug: 'savage' } },
  { path: 'blog/begrippen/scharrel', component: BlogTermComponent, title: 'Wat betekent: Scharrel?', data: { slug: 'scharrel' } },
  { path: 'blog/begrippen/screenshotting', component: BlogTermComponent, title: 'Wat betekent: Screenshotting?', data: { slug: 'screenshotting' } },
  { path: 'blog/begrippen/seeing-someone', component: BlogTermComponent, title: 'Wat betekent: Seeing someone?', data: { slug: 'seeing-someone' } },
  { path: 'blog/begrippen/semester', component: BlogTermComponent, title: 'Wat betekent: Semester?', data: { slug: 'semester' } },
  { path: 'blog/begrippen/seminar', component: BlogTermComponent, title: 'Wat betekent: Seminar?', data: { slug: 'seminar' } },
  { path: 'blog/begrippen/sending-me', component: BlogTermComponent, title: 'Wat betekent: Sending me?', data: { slug: 'sending-me' } },
  { path: 'blog/begrippen/senior', component: BlogTermComponent, title: 'Wat betekent: Senior?', data: { slug: 'senior' } },
  { path: 'blog/begrippen/sensa', component: BlogTermComponent, title: 'Wat betekent: Sensa?', data: { slug: 'sensa' } },
  { path: 'blog/begrippen/serving', component: BlogTermComponent, title: 'Wat betekent: Serving?', data: { slug: 'serving' } },
  { path: 'blog/begrippen/sexting', component: BlogTermComponent, title: 'Wat betekent: Sexting?', data: { slug: 'sexting' } },
  { path: 'blog/begrippen/sg', component: BlogTermComponent, title: 'Wat betekent: SG?', data: { slug: 'sg' } },
  { path: 'blog/begrippen/shade', component: BlogTermComponent, title: 'Wat betekent: Shade?', data: { slug: 'shade' } },
  { path: 'blog/begrippen/sharken', component: BlogTermComponent, title: 'Wat betekent: Sharken?', data: { slug: 'sharken' } },
  { path: 'blog/begrippen/shitposting', component: BlogTermComponent, title: 'Wat betekent: Shitposting?', data: { slug: 'shitposting' } },
  { path: 'blog/begrippen/shook', component: BlogTermComponent, title: 'Wat betekent: Shook?', data: { slug: 'shook' } },
  { path: 'blog/begrippen/shot', component: BlogTermComponent, title: 'Wat betekent: Shot?', data: { slug: 'shot' } },
  { path: 'blog/begrippen/shotgun-a-beer', component: BlogTermComponent, title: 'Wat betekent: Shotgun a beer?', data: { slug: 'shotgun-a-beer' } },
  { path: 'blog/begrippen/side-quest', component: BlogTermComponent, title: 'Wat betekent: Side quest?', data: { slug: 'side-quest' } },
  { path: 'blog/begrippen/simp', component: BlogTermComponent, title: 'Wat betekent: Simp?', data: { slug: 'simp' } },
  { path: 'blog/begrippen/situationship', component: BlogTermComponent, title: 'Wat betekent: Situationship?', data: { slug: 'situationship' } },
  { path: 'blog/begrippen/sjaars', component: BlogTermComponent, title: 'Wat betekent: Sjaars?', data: { slug: 'sjaars' } },
  { path: 'blog/begrippen/skeer', component: BlogTermComponent, title: 'Wat betekent: Skeer?', data: { slug: 'skeer' } },
  { path: 'blog/begrippen/slay', component: BlogTermComponent, title: 'Wat betekent: Slay?', data: { slug: 'slay' } },
  { path: 'blog/begrippen/slide-into-the-dms', component: BlogTermComponent, title: 'Wat betekent: Slide into the DMs?', data: { slug: 'slide-into-the-dms' } },
  { path: 'blog/begrippen/slow-fade', component: BlogTermComponent, title: 'Wat betekent: Slow fade?', data: { slug: 'slow-fade' } },
  { path: 'blog/begrippen/smoelen', component: BlogTermComponent, title: 'Wat betekent: Smoelen?', data: { slug: 'smoelen' } },
  { path: 'blog/begrippen/snatched', component: BlogTermComponent, title: 'Wat betekent: Snatched?', data: { slug: 'snatched' } },
  { path: 'blog/begrippen/sneaky-link', component: BlogTermComponent, title: 'Wat betekent: Sneaky link?', data: { slug: 'sneaky-link' } },
  { path: 'blog/begrippen/sober', component: BlogTermComponent, title: 'Wat betekent: Sober?', data: { slug: 'sober' } },
  { path: 'blog/begrippen/societeit', component: BlogTermComponent, title: 'Wat betekent: Sociëteit?', data: { slug: 'societeit' } },
  { path: 'blog/begrippen/soft-launch', component: BlogTermComponent, title: 'Wat betekent: Soft launch?', data: { slug: 'soft-launch' } },
  { path: 'blog/begrippen/soos', component: BlogTermComponent, title: 'Wat betekent: Soos?', data: { slug: 'soos' } },
  { path: 'blog/begrippen/sophomore', component: BlogTermComponent, title: 'Wat betekent: Sophomore?', data: { slug: 'sophomore' } },
  { path: 'blog/begrippen/sorority', component: BlogTermComponent, title: 'Wat betekent: Sorority?', data: { slug: 'sorority' } },
  { path: 'blog/begrippen/spa-goud', component: BlogTermComponent, title: 'Wat betekent: Spa goud?', data: { slug: 'spa-goud' } },
  { path: 'blog/begrippen/spam-account', component: BlogTermComponent, title: 'Wat betekent: Spam account?', data: { slug: 'spam-account' } },
  { path: 'blog/begrippen/spannie', component: BlogTermComponent, title: 'Wat betekent: Spannie?', data: { slug: 'spannie' } },
  { path: 'blog/begrippen/spiegelen', component: BlogTermComponent, title: 'Wat betekent: Spiegelen?', data: { slug: 'spiegelen' } },
  { path: 'blog/begrippen/spijtknor', component: BlogTermComponent, title: 'Wat betekent: Spijtknor?', data: { slug: 'spijtknor' } },
  { path: 'blog/begrippen/spoorknor', component: BlogTermComponent, title: 'Wat betekent: Spoorknor?', data: { slug: 'spoorknor' } },
  { path: 'blog/begrippen/stalking', component: BlogTermComponent, title: 'Wat betekent: Stalking?', data: { slug: 'stalking' } },
  { path: 'blog/begrippen/stan', component: BlogTermComponent, title: 'Wat betekent: Stan?', data: { slug: 'stan' } },
  { path: 'blog/begrippen/stiften', component: BlogTermComponent, title: 'Wat betekent: Stiften?', data: { slug: 'stiften' } },
  { path: 'blog/begrippen/stitch', component: BlogTermComponent, title: 'Wat betekent: Stitch?', data: { slug: 'stitch' } },
  { path: 'blog/begrippen/storytime', component: BlogTermComponent, title: 'Wat betekent: Storytime?', data: { slug: 'storytime' } },
  { path: 'blog/begrippen/strepen', component: BlogTermComponent, title: 'Wat betekent: Strepen?', data: { slug: 'strepen' } },
  { path: 'blog/begrippen/student', component: BlogTermComponent, title: 'Wat betekent: Student?', data: { slug: 'student' } },
  { path: 'blog/begrippen/student-union', component: BlogTermComponent, title: 'Wat betekent: Student union?', data: { slug: 'student-union' } },
  { path: 'blog/begrippen/studentenhuis', component: BlogTermComponent, title: 'Wat betekent: Studentenhuis?', data: { slug: 'studentenhuis' } },
  { path: 'blog/begrippen/studentenreisproduct', component: BlogTermComponent, title: 'Wat betekent: Studentenreisproduct?', data: { slug: 'studentenreisproduct' } },
  { path: 'blog/begrippen/studententien', component: BlogTermComponent, title: 'Wat betekent: Studententien?', data: { slug: 'studententien' } },
  { path: 'blog/begrippen/studentenvereniging', component: BlogTermComponent, title: 'Wat betekent: Studentenvereniging?', data: { slug: 'studentenvereniging' } },
  { path: 'blog/begrippen/studentikoos', component: BlogTermComponent, title: 'Wat betekent: Studentikoos?', data: { slug: 'studentikoos' } },
  { path: 'blog/begrippen/studievereniging', component: BlogTermComponent, title: 'Wat betekent: Studievereniging?', data: { slug: 'studievereniging' } },
  { path: 'blog/begrippen/study-abroad', component: BlogTermComponent, title: 'Wat betekent: Study abroad?', data: { slug: 'study-abroad' } },
  { path: 'blog/begrippen/study-buddy', component: BlogTermComponent, title: 'Wat betekent: Study buddy?', data: { slug: 'study-buddy' } },
  { path: 'blog/begrippen/study-session', component: BlogTermComponent, title: 'Wat betekent: Study session?', data: { slug: 'study-session' } },
  { path: 'blog/begrippen/stufi', component: BlogTermComponent, title: 'Wat betekent: Stufi?', data: { slug: 'stufi' } },
  { path: 'blog/begrippen/stuko', component: BlogTermComponent, title: 'Wat betekent: Stuko?', data: { slug: 'stuko' } },
  { path: 'blog/begrippen/super', component: BlogTermComponent, title: 'Wat betekent: De super?', data: { slug: 'super' } },
  { path: 'blog/begrippen/sus', component: BlogTermComponent, title: 'Wat betekent: Sus?', data: { slug: 'sus' } },
  { path: 'blog/begrippen/sws', component: BlogTermComponent, title: 'Wat betekent: SWS?', data: { slug: 'sws' } },
  { path: 'blog/begrippen/talking-stage', component: BlogTermComponent, title: 'Wat betekent: Talking stage?', data: { slug: 'talking-stage' } },
  { path: 'blog/begrippen/tbh', component: BlogTermComponent, title: 'Wat betekent: TBH?', data: { slug: 'tbh' } },
  { path: 'blog/begrippen/tea', component: BlogTermComponent, title: 'Wat betekent: Tea?', data: { slug: 'tea' } },
  { path: 'blog/begrippen/tellie', component: BlogTermComponent, title: 'Wat betekent: Tellie?', data: { slug: 'tellie' } },
  { path: 'blog/begrippen/tenta', component: BlogTermComponent, title: 'Wat betekent: Tenta?', data: { slug: 'tenta' } },
  { path: 'blog/begrippen/thesis', component: BlogTermComponent, title: 'Wat betekent: Thesis?', data: { slug: 'thesis' } },
  { path: 'blog/begrippen/thirst-trap', component: BlogTermComponent, title: 'Wat betekent: Thirst trap?', data: { slug: 'thirst-trap' } },
  { path: 'blog/begrippen/thirsty', component: BlogTermComponent, title: 'Wat betekent: Thirsty?', data: { slug: 'thirsty' } },
  { path: 'blog/begrippen/thth', component: BlogTermComponent, title: 'Wat betekent: THTH?', data: { slug: 'thth' } },
  { path: 'blog/begrippen/thuis', component: BlogTermComponent, title: 'Wat betekent: Thuis?', data: { slug: 'thuis' } },
  { path: 'blog/begrippen/thuisthuis', component: BlogTermComponent, title: 'Wat betekent: Thuisthuis?', data: { slug: 'thuisthuis' } },
  { path: 'blog/begrippen/tijgerpunten', component: BlogTermComponent, title: 'Wat betekent: Tijgerpunten?', data: { slug: 'tijgerpunten' } },
  { path: 'blog/begrippen/tjak', component: BlogTermComponent, title: 'Wat betekent: Tjak?', data: { slug: 'tjak' } },
  { path: 'blog/begrippen/tmi', component: BlogTermComponent, title: 'Wat betekent: TMI?', data: { slug: 'tmi' } },
  { path: 'blog/begrippen/toko', component: BlogTermComponent, title: 'Wat betekent: Toko?', data: { slug: 'toko' } },
  { path: 'blog/begrippen/touch-grass', component: BlogTermComponent, title: 'Wat betekent: Touch grass?', data: { slug: 'touch-grass' } },
  { path: 'blog/begrippen/toxic-relationship', component: BlogTermComponent, title: 'Wat betekent: Toxic relationship?', data: { slug: 'toxic-relationship' } },
  { path: 'blog/begrippen/tranqi', component: BlogTermComponent, title: 'Wat betekent: Tranqi?', data: { slug: 'tranqi' } },
  { path: 'blog/begrippen/tranquilo', component: BlogTermComponent, title: 'Wat betekent: Tranquilo?', data: { slug: 'tranquilo' } },
  { path: 'blog/begrippen/trekken', component: BlogTermComponent, title: 'Wat betekent: Trekken?', data: { slug: 'trekken' } },
  { path: 'blog/begrippen/trending', component: BlogTermComponent, title: 'Wat betekent: Trending?', data: { slug: 'trending' } },
  { path: 'blog/begrippen/troll', component: BlogTermComponent, title: 'Wat betekent: Troll?', data: { slug: 'troll' } },
  { path: 'blog/begrippen/turflijst', component: BlogTermComponent, title: 'Wat betekent: Turflijst?', data: { slug: 'turflijst' } },
  { path: 'blog/begrippen/tetteren', component: BlogTermComponent, title: 'Wat betekent: Tetteren?', data: { slug: 'tetteren' } },
  { path: 'blog/begrippen/tutorial', component: BlogTermComponent, title: 'Wat betekent: Tutorial?', data: { slug: 'tutorial' } },
  { path: 'blog/begrippen/ub', component: BlogTermComponent, title: 'Wat betekent: UB?', data: { slug: 'ub' } },
  { path: 'blog/begrippen/uf', component: BlogTermComponent, title: 'Wat betekent: Uf?', data: { slug: 'uf' } },
  { path: 'blog/begrippen/unhinged', component: BlogTermComponent, title: 'Wat betekent: Unhinged?', data: { slug: 'unhinged' } },
  { path: 'blog/begrippen/unpopular-opinion', component: BlogTermComponent, title: 'Wat betekent: Unpopular opinion?', data: { slug: 'unpopular-opinion' } },
  { path: 'blog/begrippen/valid', component: BlogTermComponent, title: 'Wat betekent: Valid?', data: { slug: 'valid' } },
  { path: 'blog/begrippen/vanaaf', component: BlogTermComponent, title: 'Wat betekent: Vanaaf?', data: { slug: 'vanaaf' } },
  { path: 'blog/begrippen/vestjeslikker', component: BlogTermComponent, title: 'Wat betekent: Vestjeslikker?', data: { slug: 'vestjeslikker' } },
  { path: 'blog/begrippen/veto', component: BlogTermComponent, title: 'Wat betekent: Veto?', data: { slug: 'veto' } },
  { path: 'blog/begrippen/vibe', component: BlogTermComponent, title: 'Wat betekent: Vibe?', data: { slug: 'vibe' } },
  { path: 'blog/begrippen/vibe-check', component: BlogTermComponent, title: 'Wat betekent: Vibe check?', data: { slug: 'vibe-check' } },
  { path: 'blog/begrippen/vino', component: BlogTermComponent, title: 'Wat betekent: Vino?', data: { slug: 'vino' } },
  { path: 'blog/begrippen/viral', component: BlogTermComponent, title: 'Wat betekent: Viral?', data: { slug: 'viral' } },
  { path: 'blog/begrippen/vo', component: BlogTermComponent, title: 'Wat betekent: Vo?', data: { slug: 'vo' } },
  { path: 'blog/begrippen/vozen', component: BlogTermComponent, title: 'Wat betekent: Vozen?', data: { slug: 'vozen' } },
  { path: 'blog/begrippen/vrijmibo', component: BlogTermComponent, title: 'Wat betekent: Vrijmibo?', data: { slug: 'vrijmibo' } },
  { path: 'blog/begrippen/vvv', component: BlogTermComponent, title: 'Wat betekent: VVV\'tje?', data: { slug: 'vvv' } },
  { path: 'blog/begrippen/w', component: BlogTermComponent, title: 'Wat betekent: W?', data: { slug: 'w' } },
  { path: 'blog/begrippen/walk-of-shame', component: BlogTermComponent, title: 'Wat betekent: Walk of shame?', data: { slug: 'walk-of-shame' } },
  { path: 'blog/begrippen/wegtikken', component: BlogTermComponent, title: 'Wat betekent: Wegtikken?', data: { slug: 'wegtikken' } },
  { path: 'blog/begrippen/wild', component: BlogTermComponent, title: 'Wat betekent: Wild?', data: { slug: 'wild' } },
  { path: 'blog/begrippen/wingman', component: BlogTermComponent, title: 'Wat betekent: Wingman?', data: { slug: 'wingman' } },
  { path: 'blog/begrippen/work-life-balance', component: BlogTermComponent, title: 'Wat betekent: Work-life balance?', data: { slug: 'work-life-balance' } },
  { path: 'blog/begrippen/wtf', component: BlogTermComponent, title: 'Wat betekent: WTF?', data: { slug: 'wtf' } },
  { path: 'blog/begrippen/x', component: BlogTermComponent, title: 'Wat betekent: X?', data: { slug: 'x' } },
  { path: 'blog/begrippen/yap', component: BlogTermComponent, title: 'Wat betekent: Yap?', data: { slug: 'yap' } },
  { path: 'blog/begrippen/yolo', component: BlogTermComponent, title: 'Wat betekent: YOLO?', data: { slug: 'yolo' } },
  { path: 'blog/begrippen/zeester', component: BlogTermComponent, title: 'Wat betekent: Zeester?', data: { slug: 'zeester' } },
  { path: 'blog/begrippen/zombieing', component: BlogTermComponent, title: 'Wat betekent: Zombieing?', data: { slug: 'zombieing' } },
  { path: '**', component: NotFoundComponent, title: '404 Niet gevonden' }
];
