import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { PrivacyComponent } from './pages/juridisch/privacy/privacy.component';
import { TermsComponent } from './pages/juridisch/terms/terms.component';
import { ContactComponent } from './pages/contact/contact.component';
import { NotFoundComponent } from './components/not-found/not-found.component';
import { RemoveAccountComponent } from './pages/account/remove/removeAccount.component';
import { WatIsEenAnytimer } from './pages/blogs/begrippen/wat-is-een-anytimer/wat-is-een-anytimer.component';
import { BlogComponent } from './pages/blog/blog.component';
import { DrankspellenComponent } from './pages/blogs/inspiratie/drankspellen/drankspellen.component';
import { WatIsEenAdtjeComponent } from './pages/blogs/begrippen/wat-is-een-adtje/wat-is-een-adtje.component';
import { WatIsDeBestAdtTimerComponent } from './pages/blogs/inspiratie/wat-is-de-beste-adt-timer/wat-is-de-beste-adt-timer.component';
import { MagJeEenAnyttimerWeigerenComponent } from './pages/blogs/weetjes/mag-je-een-anytimer-weigeren/mag-je-een-anytimer-weigeren.component';
import { AnytimersWhatsappNotitiesComponent } from './pages/blogs/weetjes/anytimers-bijhouden-whatsapp-notities/anytimers-bijhouden-whatsapp-notities.component';
import { HuisavondideeenComponent } from './pages/blogs/inspiratie/huisavondideeen/huisavondideeen.component';
import { JeuDeBierComponent } from './pages/blogs/drankspelletjes/jeu-de-bier/jeu-de-bier.component';
import { BlogCategoryComponent } from './pages/blog-category/blog-category.component';
import { MarioBarfComponent } from './pages/blogs/drankspelletjes/mario-barf/mario-barf.component';
import { TrekJeBakManiaComponent } from './pages/blogs/drankspelletjes/trek-je-bak-mania/trek-je-bak-mania.component';
import { ThirtySecondsComponent } from './pages/blogs/drankspelletjes/30-seconds/30-seconds.component';
import { KingsenComponent } from './pages/blogs/drankspelletjes/kingsen/kingsen.component';
import { StressPongComponent } from './pages/blogs/drankspelletjes/stress-pong/stress-pong.component';
import { FuckTheDealerComponent } from './pages/blogs/drankspelletjes/fuck-the-dealer/fuck-the-dealer.component';
import { MexenComponent } from './pages/blogs/drankspelletjes/mexen/mexen.component';
import { BakplatenComponent } from './pages/blogs/drankspelletjes/bakplaten/bakplaten.component';
import { DePaardenraceComponent } from './pages/blogs/drankspelletjes/de-paardenrace/de-paardenrace.component';
import { RingOfFireComponent } from './pages/blogs/drankspelletjes/ring-of-fire/ring-of-fire.component';
import { MijnenveldComponent } from './pages/blogs/drankspelletjes/mijnenveld/mijnenveld.component';
import { StefStuntpilootComponent } from './pages/blogs/drankspelletjes/stef-stuntpiloot/stef-stuntpiloot.component';
import { VingerenComponent } from './pages/blogs/drankspelletjes/vingeren/vingeren.component';
import { VikingenComponent } from './pages/blogs/drankspelletjes/vikingen/vikingen.component';
import { ZeeslagComponent } from './pages/blogs/drankspelletjes/zeeslag/zeeslag.component';
import { KusjeGevenComponent } from './pages/blogs/drankspelletjes/kusje-geven/kusje-geven.component';
import { BussenComponent } from './pages/blogs/drankspelletjes/bussen/bussen.component';
import { HogerLagerComponent } from './pages/blogs/drankspelletjes/hoger-lager/hoger-lager.component';
import { KrokodillenspelComponent } from './pages/blogs/drankspelletjes/krokodillenspel/krokodillenspel.component';
import { BlogTermComponent } from './pages/blog-term/blog-term.component';

export const routes: Routes = [
  { path: '', component: HomeComponent, title: 'AnyTimerApp - De app om je anytimers in bij te houden' },
  { path: 'privacy', component: PrivacyComponent, title: 'Privacybeleid AnyTimerApp - AVG-Conform & Veilig' },
  { path: 'remove-account', component: RemoveAccountComponent, title: 'Account Verwijderen AnyTimerApp - Stap-voor-Stap Gids' },
  { path: 'terms', component: TermsComponent, title: 'Gebruiksvoorwaarden AnyTimerApp - Regels & Voorwaarden' },
  { path: 'contact', component: ContactComponent, title: 'Contact AnyTimerApp - Vragen, Feedback & Samenwerking' },
  { path: 'blog', component: BlogComponent, title: 'AnyTimerApp Blog - Tips, Ideeën & Gidsen' },
  { path: 'blog/begrippen', component: BlogCategoryComponent, title: 'Anytimer Begrippen Uitgelegd | AnyTimerApp', data: { category: 'Begrippen' } },
  { path: 'blog/inspiratie', component: BlogCategoryComponent, title: 'Inspiratie voor een Leuke Avond | AnyTimerApp', data: { category: 'Inspiratie' } },
  { path: 'blog/weetjes', component: BlogCategoryComponent, title: 'Anytimer Weetjes & Regels | AnyTimerApp', data: { category: 'Weetjes' } },
  { path: 'blog/drankspelletjes', component: BlogCategoryComponent, title: 'Drankspelletjes: Spelregels & Tips | AnyTimerApp', data: { category: 'Drankspelletjes' } },
  { path: 'drankspellen', component: DrankspellenComponent, title: 'Top 10 Leukste Drankspellen voor een Gezellige Avond | AnyTimerApp' },
  { path: 'wat-is-een-anytimer', component: WatIsEenAnytimer, title: 'Wat is een Anytimer? - Gids & Uitleg | AnyTimerApp' },
  { path: 'wat-is-een-adtje', component: WatIsEenAdtjeComponent, title: 'Wat is een Adtje? - Gids & Uitleg | AnyTimerApp' },
  { path: 'wat-is-de-beste-adt-timer', component: WatIsDeBestAdtTimerComponent, title: 'Wat is de Beste Adt Timer? - Gids & Opties | AnyTimerApp' },
  { path: 'mag-je-een-anytimer-weigeren', component: MagJeEenAnyttimerWeigerenComponent, title: 'Mag je een Anytimer Weigeren? - Regels & Gevolgen | AnyTimerApp' },
  { path: 'anytimers-bijhouden-whatsapp-notities', component: AnytimersWhatsappNotitiesComponent, title: 'Waarom je Anytimers niet in WhatsApp of Notities Bijhoudt | AnyTimerApp' },
  { path: 'huisavondideeen', component: HuisavondideeenComponent, title: 'Top 10 Leuke Huisavondideeën | AnyTimerApp' },
  { path: 'blog/drankspelletjes/jeu-de-bier', component: JeuDeBierComponent, title: 'Jeu de Bier - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/mario-barf', component: MarioBarfComponent, title: 'Mario Barf - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/trek-je-bak-mania', component: TrekJeBakManiaComponent, title: 'Trek je Bak Mania - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/30-seconds', component: ThirtySecondsComponent, title: '30 Seconds - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/kingsen', component: KingsenComponent, title: 'Kingsen - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/stress-pong', component: StressPongComponent, title: 'Stress Pong - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/fuck-the-dealer', component: FuckTheDealerComponent, title: 'Fuck the Dealer - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/mexen', component: MexenComponent, title: 'Mexen - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/bakplaten', component: BakplatenComponent, title: 'Bakplaten - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/de-paardenrace', component: DePaardenraceComponent, title: 'De Paardenrace - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/ring-of-fire', component: RingOfFireComponent, title: 'Ring of fire - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/mijnenveld', component: MijnenveldComponent, title: 'Mijnenveld - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/stef-stuntpiloot', component: StefStuntpilootComponent, title: 'Stef stuntpiloot - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/vingeren', component: VingerenComponent, title: 'Vingeren - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/vikingen', component: VikingenComponent, title: 'Vikingen - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/zeeslag', component: ZeeslagComponent, title: 'Zeeslag - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/kusje-geven', component: KusjeGevenComponent, title: 'Kusje geven - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/bussen', component: BussenComponent, title: 'Bussen - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/hoger-lager', component: HogerLagerComponent, title: 'Hoger lager - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/drankspelletjes/krokodillenspel', component: KrokodillenspelComponent, title: 'Krokodillenspel - Spelregels & Tips | AnyTimerApp' },
  { path: 'blog/begrippen/ab-actis', component: BlogTermComponent, title: 'Wat betekent: Ab actis?', data: { slug: 'ab-actis' } },
  { path: 'blog/begrippen/abbo', component: BlogTermComponent, title: 'Wat betekent: Abbo?', data: { slug: 'abbo' } },
  { path: 'blog/begrippen/adten', component: BlogTermComponent, title: 'Wat betekent: Adten?', data: { slug: 'adten' } },
  { path: 'blog/begrippen/adtje-des', component: BlogTermComponent, title: 'Wat betekent: Adtje des?', data: { slug: 'adtje-des' } },
  { path: 'blog/begrippen/adtje-herhaling', component: BlogTermComponent, title: 'Wat betekent: Adtje herhaling?', data: { slug: 'adtje-herhaling' } },
  { path: 'blog/begrippen/adtje-kratje', component: BlogTermComponent, title: 'Wat betekent: Adtje kratje?', data: { slug: 'adtje-kratje' } },
  { path: 'blog/begrippen/adtje-solidair', component: BlogTermComponent, title: 'Wat betekent: Adtje solidair?', data: { slug: 'adtje-solidair' } },
  { path: 'blog/begrippen/afko', component: BlogTermComponent, title: 'Wat betekent: Afko?', data: { slug: 'afko' } },
  { path: 'blog/begrippen/afpilsen', component: BlogTermComponent, title: 'Wat betekent: Afpilsen?', data: { slug: 'afpilsen' } },
  { path: 'blog/begrippen/afstubo', component: BlogTermComponent, title: 'Wat betekent: Afstubo?', data: { slug: 'afstubo' } },
  { path: 'blog/begrippen/airfryer', component: BlogTermComponent, title: 'Wat betekent: Airfryer?', data: { slug: 'airfryer' } },
  { path: 'blog/begrippen/al', component: BlogTermComponent, title: 'Wat betekent: AL?', data: { slug: 'al' } },
  { path: 'blog/begrippen/almanak', component: BlogTermComponent, title: 'Wat betekent: Almanak?', data: { slug: 'almanak' } },
  { path: 'blog/begrippen/alv', component: BlogTermComponent, title: 'Wat betekent: ALV?', data: { slug: 'alv' } },
  { path: 'blog/begrippen/ambu', component: BlogTermComponent, title: 'Wat betekent: Ambu?', data: { slug: 'ambu' } },
  { path: 'blog/begrippen/amice', component: BlogTermComponent, title: 'Wat betekent: Amice?', data: { slug: 'amice' } },
  { path: 'blog/begrippen/arbeider', component: BlogTermComponent, title: 'Wat betekent: Arbeider?', data: { slug: 'arbeider' } },
  { path: 'blog/begrippen/assessor', component: BlogTermComponent, title: 'Wat betekent: Assessor?', data: { slug: 'assessor' } },
  { path: 'blog/begrippen/baco', component: BlogTermComponent, title: 'Wat betekent: Baco?', data: { slug: 'baco' } },
  { path: 'blog/begrippen/bak-trekken', component: BlogTermComponent, title: 'Wat betekent: Bak trekken?', data: { slug: 'bak-trekken' } },
  { path: 'blog/begrippen/bakken-vouwen', component: BlogTermComponent, title: 'Wat betekent: Bakken vouwen?', data: { slug: 'bakken-vouwen' } },
  { path: 'blog/begrippen/bal', component: BlogTermComponent, title: 'Wat betekent: Bal?', data: { slug: 'bal' } },
  { path: 'blog/begrippen/barco', component: BlogTermComponent, title: 'Wat betekent: Barco?', data: { slug: 'barco' } },
  { path: 'blog/begrippen/barf', component: BlogTermComponent, title: 'Wat betekent: Barf?', data: { slug: 'barf' } },
  { path: 'blog/begrippen/batsen', component: BlogTermComponent, title: 'Wat betekent: Batsen?', data: { slug: 'batsen' } },
  { path: 'blog/begrippen/berig', component: BlogTermComponent, title: 'Wat betekent: Berig?', data: { slug: 'berig' } },
  { path: 'blog/begrippen/bestuur', component: BlogTermComponent, title: 'Wat betekent: Bestuur?', data: { slug: 'bestuur' } },
  { path: 'blog/begrippen/bij', component: BlogTermComponent, title: 'Wat betekent: Bij?', data: { slug: 'bij' } },
  { path: 'blog/begrippen/bits', component: BlogTermComponent, title: 'Wat betekent: Bits?', data: { slug: 'bits' } },
  { path: 'blog/begrippen/bodem-leggen', component: BlogTermComponent, title: 'Wat betekent: Bodem leggen?', data: { slug: 'bodem-leggen' } },
  { path: 'blog/begrippen/brak', component: BlogTermComponent, title: 'Wat betekent: Brak?', data: { slug: 'brak' } },
  { path: 'blog/begrippen/braken', component: BlogTermComponent, title: 'Wat betekent: Braken?', data: { slug: 'braken' } },
  { path: 'blog/begrippen/brassen', component: BlogTermComponent, title: 'Wat betekent: Brassen?', data: { slug: 'brassen' } },
  { path: 'blog/begrippen/bs', component: BlogTermComponent, title: 'Wat betekent: Bs?', data: { slug: 'bs' } },
  { path: 'blog/begrippen/bueno', component: BlogTermComponent, title: 'Wat betekent: Bueno?', data: { slug: 'bueno' } },
  { path: 'blog/begrippen/burger', component: BlogTermComponent, title: 'Wat betekent: Burger?', data: { slug: 'burger' } },
  { path: 'blog/begrippen/burgerrups', component: BlogTermComponent, title: 'Wat betekent: Burgerrups?', data: { slug: 'burgerrups' } },
  { path: 'blog/begrippen/bv', component: BlogTermComponent, title: 'Wat betekent: Bv?', data: { slug: 'bv' } },
  { path: 'blog/begrippen/bvo', component: BlogTermComponent, title: 'Wat betekent: Bvo?', data: { slug: 'bvo' } },
  { path: 'blog/begrippen/byob', component: BlogTermComponent, title: 'Wat betekent: BYOB?', data: { slug: 'byob' } },
  { path: 'blog/begrippen/bsa', component: BlogTermComponent, title: 'Wat betekent: BSA?', data: { slug: 'bsa' } },
  { path: 'blog/begrippen/cappu', component: BlogTermComponent, title: 'Wat betekent: Cappu?', data: { slug: 'cappu' } },
  { path: 'blog/begrippen/chlam', component: BlogTermComponent, title: 'Wat betekent: Chlam?', data: { slug: 'chlam' } },
  { path: 'blog/begrippen/condo', component: BlogTermComponent, title: 'Wat betekent: Condo?', data: { slug: 'condo' } },
  { path: 'blog/begrippen/connie', component: BlogTermComponent, title: 'Wat betekent: Connie?', data: { slug: 'connie' } },
  { path: 'blog/begrippen/constitutieborrel', component: BlogTermComponent, title: 'Wat betekent: Constitutieborrel?', data: { slug: 'constitutieborrel' } },
  { path: 'blog/begrippen/corps', component: BlogTermComponent, title: 'Wat betekent: Corps?', data: { slug: 'corps' } },
  { path: 'blog/begrippen/cursist', component: BlogTermComponent, title: 'Wat betekent: Cursist?', data: { slug: 'cursist' } },
  { path: 'blog/begrippen/cursus', component: BlogTermComponent, title: 'Wat betekent: Cursus?', data: { slug: 'cursus' } },
  { path: 'blog/begrippen/commissie', component: BlogTermComponent, title: 'Wat betekent: Commissie?', data: { slug: 'commissie' } },
  { path: 'blog/begrippen/dapri', component: BlogTermComponent, title: 'Wat betekent: Dapri?', data: { slug: 'dapri' } },
  { path: 'blog/begrippen/das', component: BlogTermComponent, title: 'Wat betekent: Das?', data: { slug: 'das' } },
  { path: 'blog/begrippen/datediner', component: BlogTermComponent, title: 'Wat betekent: Datediner?', data: { slug: 'datediner' } },
  { path: 'blog/begrippen/despo', component: BlogTermComponent, title: 'Wat betekent: Despo?', data: { slug: 'despo' } },
  { path: 'blog/begrippen/deur-verdienen', component: BlogTermComponent, title: 'Wat betekent: Deur verdienen?', data: { slug: 'deur-verdienen' } },
  { path: 'blog/begrippen/dibs', component: BlogTermComponent, title: 'Wat betekent: Dibs?', data: { slug: 'dibs' } },
  { path: 'blog/begrippen/dichtgetikt', component: BlogTermComponent, title: 'Wat betekent: Dichtgetikt?', data: { slug: 'dichtgetikt' } },
  { path: 'blog/begrippen/dies', component: BlogTermComponent, title: 'Wat betekent: Dies?', data: { slug: 'dies' } },
  { path: 'blog/begrippen/dispuut', component: BlogTermComponent, title: 'Wat betekent: Dispuut?', data: { slug: 'dispuut' } },
  { path: 'blog/begrippen/doorhalen', component: BlogTermComponent, title: 'Wat betekent: Doorhalen?', data: { slug: 'doorhalen' } },
  { path: 'blog/begrippen/driesecondenregel', component: BlogTermComponent, title: 'Wat betekent: Driesecondenregel?', data: { slug: 'driesecondenregel' } },
  { path: 'blog/begrippen/dubbel-gemengd', component: BlogTermComponent, title: 'Wat betekent: Dubbel gemengd?', data: { slug: 'dubbel-gemengd' } },
  { path: 'blog/begrippen/duft', component: BlogTermComponent, title: 'Wat betekent: Duft?', data: { slug: 'duft' } },
  { path: 'blog/begrippen/duo', component: BlogTermComponent, title: 'Wat betekent: DUO?', data: { slug: 'duo' } },
  { path: 'blog/begrippen/droog-staan', component: BlogTermComponent, title: 'Wat betekent: Droog staan?', data: { slug: 'droog-staan' } },
  { path: 'blog/begrippen/el-cid', component: BlogTermComponent, title: 'Wat betekent: EL CID?', data: { slug: 'el-cid' } },
  { path: 'blog/begrippen/esca', component: BlogTermComponent, title: 'Wat betekent: Esca?', data: { slug: 'esca' } },
  { path: 'blog/begrippen/escaleren', component: BlogTermComponent, title: 'Wat betekent: Escaleren?', data: { slug: 'escaleren' } },
  { path: 'blog/begrippen/esma', component: BlogTermComponent, title: 'Wat betekent: Esma?', data: { slug: 'esma' } },
  { path: 'blog/begrippen/eventuela', component: BlogTermComponent, title: 'Wat betekent: Eventuela?', data: { slug: 'eventuela' } },
  { path: 'blog/begrippen/exclu', component: BlogTermComponent, title: 'Wat betekent: Exclu?', data: { slug: 'exclu' } },
  { path: 'blog/begrippen/exclusief', component: BlogTermComponent, title: 'Wat betekent: Exclusief?', data: { slug: 'exclusief' } },
  { path: 'blog/begrippen/extern', component: BlogTermComponent, title: 'Wat betekent: Extern?', data: { slug: 'extern' } },
  { path: 'blog/begrippen/feut', component: BlogTermComponent, title: 'Wat betekent: Feut?', data: { slug: 'feut' } },
  { path: 'blog/begrippen/flaneren', component: BlogTermComponent, title: 'Wat betekent: Flaneren?', data: { slug: 'flaneren' } },
  { path: 'blog/begrippen/fomo', component: BlogTermComponent, title: 'Wat betekent: FOMO?', data: { slug: 'fomo' } },
  { path: 'blog/begrippen/fuif', component: BlogTermComponent, title: 'Wat betekent: Fuif?', data: { slug: 'fuif' } },
  { path: 'blog/begrippen/fusie', component: BlogTermComponent, title: 'Wat betekent: Fusie?', data: { slug: 'fusie' } },
  { path: 'blog/begrippen/fwb', component: BlogTermComponent, title: 'Wat betekent: FWB?', data: { slug: 'fwb' } },
  { path: 'blog/begrippen/galaplicht', component: BlogTermComponent, title: 'Wat betekent: Galaplicht?', data: { slug: 'galaplicht' } },
  { path: 'blog/begrippen/gefeli', component: BlogTermComponent, title: 'Wat betekent: Gefeli?', data: { slug: 'gefeli' } },
  { path: 'blog/begrippen/geru', component: BlogTermComponent, title: 'Wat betekent: Geru?', data: { slug: 'geru' } },
  { path: 'blog/begrippen/gezel', component: BlogTermComponent, title: 'Wat betekent: Gezel?', data: { slug: 'gezel' } },
  { path: 'blog/begrippen/ginto', component: BlogTermComponent, title: 'Wat betekent: GinTo?', data: { slug: 'ginto' } },
  { path: 'blog/begrippen/gk', component: BlogTermComponent, title: 'Wat betekent: GK?', data: { slug: 'gk' } },
  { path: 'blog/begrippen/goos', component: BlogTermComponent, title: 'Wat betekent: Goos?', data: { slug: 'goos' } },
  { path: 'blog/begrippen/gozer', component: BlogTermComponent, title: 'Wat betekent: Gozer?', data: { slug: 'gozer' } },
  { path: 'blog/begrippen/gr', component: BlogTermComponent, title: 'Wat betekent: GR?', data: { slug: 'gr' } },
  { path: 'blog/begrippen/grondpannenkoek', component: BlogTermComponent, title: 'Wat betekent: Grondpannenkoek?', data: { slug: 'grondpannenkoek' } },
  { path: 'blog/begrippen/grondpizza', component: BlogTermComponent, title: 'Wat betekent: Grondpizza?', data: { slug: 'grondpizza' } },
  { path: 'blog/begrippen/guac', component: BlogTermComponent, title: 'Wat betekent: Guac?', data: { slug: 'guac' } },
  { path: 'blog/begrippen/haasje', component: BlogTermComponent, title: 'Wat betekent: Haasje?', data: { slug: 'haasje' } },
  { path: 'blog/begrippen/halve-leo', component: BlogTermComponent, title: 'Wat betekent: Halve leo?', data: { slug: 'halve-leo' } },
  { path: 'blog/begrippen/her', component: BlogTermComponent, title: 'Wat betekent: Her?', data: { slug: 'her' } },
  { path: 'blog/begrippen/hertje', component: BlogTermComponent, title: 'Wat betekent: Hertje?', data: { slug: 'hertje' } },
  { path: 'blog/begrippen/hg', component: BlogTermComponent, title: 'Wat betekent: HG?', data: { slug: 'hg' } },
  { path: 'blog/begrippen/hila', component: BlogTermComponent, title: 'Wat betekent: Hila?', data: { slug: 'hila' } },
  { path: 'blog/begrippen/hj', component: BlogTermComponent, title: 'Wat betekent: HJ?', data: { slug: 'hj' } },
  { path: 'blog/begrippen/honk', component: BlogTermComponent, title: 'Wat betekent: Honk?', data: { slug: 'honk' } },
  { path: 'blog/begrippen/hospi', component: BlogTermComponent, title: 'Wat betekent: Hospi?', data: { slug: 'hospi' } },
  { path: 'blog/begrippen/hospiteren', component: BlogTermComponent, title: 'Wat betekent: Hospiteren?', data: { slug: 'hospiteren' } },
  { path: 'blog/begrippen/houdini', component: BlogTermComponent, title: 'Wat betekent: Houdini?', data: { slug: 'houdini' } },
  { path: 'blog/begrippen/huig-hockeyen', component: BlogTermComponent, title: 'Wat betekent: Huig hockeyen?', data: { slug: 'huig-hockeyen' } },
  { path: 'blog/begrippen/huisjongste', component: BlogTermComponent, title: 'Wat betekent: Huisjongste?', data: { slug: 'huisjongste' } },
  { path: 'blog/begrippen/huispanda', component: BlogTermComponent, title: 'Wat betekent: Huispanda?', data: { slug: 'huispanda' } },
  { path: 'blog/begrippen/huisparasiet', component: BlogTermComponent, title: 'Wat betekent: Huisparasiet?', data: { slug: 'huisparasiet' } },
  { path: 'blog/begrippen/hv', component: BlogTermComponent, title: 'Wat betekent: HV?', data: { slug: 'hv' } },
  { path: 'blog/begrippen/herstelbiertje', component: BlogTermComponent, title: 'Wat betekent: Herstelbiertje?', data: { slug: 'herstelbiertje' } },
  { path: 'blog/begrippen/ibu', component: BlogTermComponent, title: 'Wat betekent: Ibu?', data: { slug: 'ibu' } },
  { path: 'blog/begrippen/icen', component: BlogTermComponent, title: 'Wat betekent: Icen?', data: { slug: 'icen' } },
  { path: 'blog/begrippen/ijskast', component: BlogTermComponent, title: 'Wat betekent: IJskast?', data: { slug: 'ijskast' } },
  { path: 'blog/begrippen/inauguratie', component: BlogTermComponent, title: 'Wat betekent: Inauguratie?', data: { slug: 'inauguratie' } },
  { path: 'blog/begrippen/indikken', component: BlogTermComponent, title: 'Wat betekent: Indikken?', data: { slug: 'indikken' } },
  { path: 'blog/begrippen/indrinken', component: BlogTermComponent, title: 'Wat betekent: Indrinken?', data: { slug: 'indrinken' } },
  { path: 'blog/begrippen/influ', component: BlogTermComponent, title: 'Wat betekent: Influ?', data: { slug: 'influ' } },
  { path: 'blog/begrippen/inkakken', component: BlogTermComponent, title: 'Wat betekent: Inkakken?', data: { slug: 'inkakken' } },
  { path: 'blog/begrippen/instemmen', component: BlogTermComponent, title: 'Wat betekent: Instemmen?', data: { slug: 'instemmen' } },
  { path: 'blog/begrippen/internacho', component: BlogTermComponent, title: 'Wat betekent: Internacho?', data: { slug: 'internacho' } },
  { path: 'blog/begrippen/introductieweek', component: BlogTermComponent, title: 'Wat betekent: Introductieweek?', data: { slug: 'introductieweek' } },
  { path: 'blog/begrippen/italiaans-afscheid', component: BlogTermComponent, title: 'Wat betekent: Italiaans afscheid?', data: { slug: 'italiaans-afscheid' } },
  { path: 'blog/begrippen/jaarclub', component: BlogTermComponent, title: 'Wat betekent: Jaarclub?', data: { slug: 'jaarclub' } },
  { path: 'blog/begrippen/jasje-dasje', component: BlogTermComponent, title: 'Wat betekent: Jasje dasje?', data: { slug: 'jasje-dasje' } },
  { path: 'blog/begrippen/jc', component: BlogTermComponent, title: 'Wat betekent: JC?', data: { slug: 'jc' } },
  { path: 'blog/begrippen/jagerbomb', component: BlogTermComponent, title: 'Wat betekent: Jägerbomb?', data: { slug: 'jagerbomb' } },
  { path: 'blog/begrippen/kaasschaaf', component: BlogTermComponent, title: 'Wat betekent: Kaasschaaf?', data: { slug: 'kaasschaaf' } },
  { path: 'blog/begrippen/kantelen', component: BlogTermComponent, title: 'Wat betekent: Kantelen?', data: { slug: 'kantelen' } },
  { path: 'blog/begrippen/kapstokhertje', component: BlogTermComponent, title: 'Wat betekent: Kapstokhertje?', data: { slug: 'kapstokhertje' } },
  { path: 'blog/begrippen/kater', component: BlogTermComponent, title: 'Wat betekent: Kater?', data: { slug: 'kater' } },
  { path: 'blog/begrippen/kmt', component: BlogTermComponent, title: 'Wat betekent: KMT?', data: { slug: 'kmt' } },
  { path: 'blog/begrippen/knor', component: BlogTermComponent, title: 'Wat betekent: Knor?', data: { slug: 'knor' } },
  { path: 'blog/begrippen/kompaan', component: BlogTermComponent, title: 'Wat betekent: Kompaan?', data: { slug: 'kompaan' } },
  { path: 'blog/begrippen/kot', component: BlogTermComponent, title: 'Wat betekent: Kot?', data: { slug: 'kot' } },
  { path: 'blog/begrippen/krokant', component: BlogTermComponent, title: 'Wat betekent: Krokant?', data: { slug: 'krokant' } },
  { path: 'blog/begrippen/kruipafstand', component: BlogTermComponent, title: 'Wat betekent: Kruipafstand?', data: { slug: 'kruipafstand' } },
  { path: 'blog/begrippen/kwarrel', component: BlogTermComponent, title: 'Wat betekent: Kwarrel?', data: { slug: 'kwarrel' } },
  { path: 'blog/begrippen/labo', component: BlogTermComponent, title: 'Wat betekent: Labo?', data: { slug: 'labo' } },
  { path: 'blog/begrippen/leenstelsel', component: BlogTermComponent, title: 'Wat betekent: Leenstelsel?', data: { slug: 'leenstelsel' } },
  { path: 'blog/begrippen/loca', component: BlogTermComponent, title: 'Wat betekent: Loca?', data: { slug: 'loca' } },
  { path: 'blog/begrippen/louter', component: BlogTermComponent, title: 'Wat betekent: Louter?', data: { slug: 'louter' } },
  { path: 'blog/begrippen/ludiek', component: BlogTermComponent, title: 'Wat betekent: Ludiek?', data: { slug: 'ludiek' } },
  { path: 'blog/begrippen/lullepot', component: BlogTermComponent, title: 'Wat betekent: Lullepot?', data: { slug: 'lullepot' } },
  { path: 'blog/begrippen/lustrum', component: BlogTermComponent, title: 'Wat betekent: Lustrum?', data: { slug: 'lustrum' } },
  { path: 'blog/begrippen/lapswans', component: BlogTermComponent, title: 'Wat betekent: Lapswans?', data: { slug: 'lapswans' } },
  { path: 'blog/begrippen/m', component: BlogTermComponent, title: 'Wat betekent: M?', data: { slug: 'm' } },
  { path: 'blog/begrippen/maat', component: BlogTermComponent, title: 'Wat betekent: Maat?', data: { slug: 'maat' } },
  { path: 'blog/begrippen/matras', component: BlogTermComponent, title: 'Wat betekent: Matras?', data: { slug: 'matras' } },
  { path: 'blog/begrippen/mc', component: BlogTermComponent, title: 'Wat betekent: MC?', data: { slug: 'mc' } },
  { path: 'blog/begrippen/mdm', component: BlogTermComponent, title: 'Wat betekent: MDM?', data: { slug: 'mdm' } },
  { path: 'blog/begrippen/medium', component: BlogTermComponent, title: 'Wat betekent: Medium?', data: { slug: 'medium' } },
  { path: 'blog/begrippen/meter-bier', component: BlogTermComponent, title: 'Wat betekent: Meter?', data: { slug: 'meter-bier' } },
  { path: 'blog/begrippen/miemelen', component: BlogTermComponent, title: 'Wat betekent: Miemelen?', data: { slug: 'miemelen' } },
  { path: 'blog/begrippen/mores', component: BlogTermComponent, title: 'Wat betekent: Mores?', data: { slug: 'mores' } },
  { path: 'blog/begrippen/mattie', component: BlogTermComponent, title: 'Wat betekent: Mattie?', data: { slug: 'mattie' } },
  { path: 'blog/begrippen/nakkie', component: BlogTermComponent, title: 'Wat betekent: Nakkie?', data: { slug: 'nakkie' } },
  { path: 'blog/begrippen/nominaal-lopen', component: BlogTermComponent, title: 'Wat betekent: Nominaal lopen?', data: { slug: 'nominaal-lopen' } },
  { path: 'blog/begrippen/normi', component: BlogTermComponent, title: 'Wat betekent: Normi?', data: { slug: 'normi' } },
  { path: 'blog/begrippen/nul', component: BlogTermComponent, title: 'Wat betekent: Nul?', data: { slug: 'nul' } },
  { path: 'blog/begrippen/nekken', component: BlogTermComponent, title: 'Wat betekent: Nekken?', data: { slug: 'nekken' } },
  { path: 'blog/begrippen/one-night-stand', component: BlogTermComponent, title: 'Wat betekent: One-night stand?', data: { slug: 'one-night-stand' } },
  { path: 'blog/begrippen/ontgroening', component: BlogTermComponent, title: 'Wat betekent: Ontgroening?', data: { slug: 'ontgroening' } },
  { path: 'blog/begrippen/p', component: BlogTermComponent, title: 'Wat betekent: P?', data: { slug: 'p' } },
  { path: 'blog/begrippen/pabo', component: BlogTermComponent, title: 'Wat betekent: Pabo?', data: { slug: 'pabo' } },
  { path: 'blog/begrippen/paklijst', component: BlogTermComponent, title: 'Wat betekent: Paklijst?', data: { slug: 'paklijst' } },
  { path: 'blog/begrippen/pandapunten', component: BlogTermComponent, title: 'Wat betekent: Pandapunten?', data: { slug: 'pandapunten' } },
  { path: 'blog/begrippen/para', component: BlogTermComponent, title: 'Wat betekent: Para?', data: { slug: 'para' } },
  { path: 'blog/begrippen/pauper', component: BlogTermComponent, title: 'Wat betekent: Pauper?', data: { slug: 'pauper' } },
  { path: 'blog/begrippen/pechgeneratie', component: BlogTermComponent, title: 'Wat betekent: Pechgeneratie?', data: { slug: 'pechgeneratie' } },
  { path: 'blog/begrippen/pint', component: BlogTermComponent, title: 'Wat betekent: Pint?', data: { slug: 'pint' } },
  { path: 'blog/begrippen/pinten-harken', component: BlogTermComponent, title: 'Wat betekent: Pinten harken?', data: { slug: 'pinten-harken' } },
  { path: 'blog/begrippen/plafonddienst', component: BlogTermComponent, title: 'Wat betekent: Plafonddienst?', data: { slug: 'plafonddienst' } },
  { path: 'blog/begrippen/praeses', component: BlogTermComponent, title: 'Wat betekent: Praeses?', data: { slug: 'praeses' } },
  { path: 'blog/begrippen/prela', component: BlogTermComponent, title: 'Wat betekent: Prela?', data: { slug: 'prela' } },
  { path: 'blog/begrippen/proleet', component: BlogTermComponent, title: 'Wat betekent: Proleet?', data: { slug: 'proleet' } },
  { path: 'blog/begrippen/promi', component: BlogTermComponent, title: 'Wat betekent: Promi?', data: { slug: 'promi' } },
  { path: 'blog/begrippen/prominent', component: BlogTermComponent, title: 'Wat betekent: Prominent?', data: { slug: 'prominent' } },
  { path: 'blog/begrippen/propedeuse', component: BlogTermComponent, title: 'Wat betekent: Propedeuse?', data: { slug: 'propedeuse' } },
  { path: 'blog/begrippen/quaestor-quaestrix', component: BlogTermComponent, title: 'Wat betekent: Quaestor / Quaestrix?', data: { slug: 'quaestor-quaestrix' } },
  { path: 'blog/begrippen/rattentaxi', component: BlogTermComponent, title: 'Wat betekent: Rattentaxi?', data: { slug: 'rattentaxi' } },
  { path: 'blog/begrippen/regelen', component: BlogTermComponent, title: 'Wat betekent: Regelen?', data: { slug: 'regelen' } },
  { path: 'blog/begrippen/regenjas', component: BlogTermComponent, title: 'Wat betekent: Regenjas?', data: { slug: 'regenjas' } },
  { path: 'blog/begrippen/rela', component: BlogTermComponent, title: 'Wat betekent: Rela?', data: { slug: 'rela' } },
  { path: 'blog/begrippen/reparadler', component: BlogTermComponent, title: 'Wat betekent: Reparadler?', data: { slug: 'reparadler' } },
  { path: 'blog/begrippen/reunist', component: BlogTermComponent, title: 'Wat betekent: Reünist?', data: { slug: 'reunist' } },
  { path: 'blog/begrippen/riet', component: BlogTermComponent, title: 'Wat betekent: Riet?', data: { slug: 'riet' } },
  { path: 'blog/begrippen/rietadt', component: BlogTermComponent, title: 'Wat betekent: Rietadt?', data: { slug: 'rietadt' } },
  { path: 'blog/begrippen/rietbak', component: BlogTermComponent, title: 'Wat betekent: Rietbak?', data: { slug: 'rietbak' } },
  { path: 'blog/begrippen/safedate', component: BlogTermComponent, title: 'Wat betekent: Safedate?', data: { slug: 'safedate' } },
  { path: 'blog/begrippen/scharrel', component: BlogTermComponent, title: 'Wat betekent: Scharrel?', data: { slug: 'scharrel' } },
  { path: 'blog/begrippen/semester', component: BlogTermComponent, title: 'Wat betekent: Semester?', data: { slug: 'semester' } },
  { path: 'blog/begrippen/sensa', component: BlogTermComponent, title: 'Wat betekent: Sensa?', data: { slug: 'sensa' } },
  { path: 'blog/begrippen/sg', component: BlogTermComponent, title: 'Wat betekent: SG?', data: { slug: 'sg' } },
  { path: 'blog/begrippen/sharken', component: BlogTermComponent, title: 'Wat betekent: Sharken?', data: { slug: 'sharken' } },
  { path: 'blog/begrippen/sjaars', component: BlogTermComponent, title: 'Wat betekent: Sjaars?', data: { slug: 'sjaars' } },
  { path: 'blog/begrippen/skeer', component: BlogTermComponent, title: 'Wat betekent: Skeer?', data: { slug: 'skeer' } },
  { path: 'blog/begrippen/smoelen', component: BlogTermComponent, title: 'Wat betekent: Smoelen?', data: { slug: 'smoelen' } },
  { path: 'blog/begrippen/societeit', component: BlogTermComponent, title: 'Wat betekent: Sociëteit?', data: { slug: 'societeit' } },
  { path: 'blog/begrippen/soos', component: BlogTermComponent, title: 'Wat betekent: Soos?', data: { slug: 'soos' } },
  { path: 'blog/begrippen/spa-goud', component: BlogTermComponent, title: 'Wat betekent: Spa goud?', data: { slug: 'spa-goud' } },
  { path: 'blog/begrippen/spannie', component: BlogTermComponent, title: 'Wat betekent: Spannie?', data: { slug: 'spannie' } },
  { path: 'blog/begrippen/spiegelen', component: BlogTermComponent, title: 'Wat betekent: Spiegelen?', data: { slug: 'spiegelen' } },
  { path: 'blog/begrippen/spijtknor', component: BlogTermComponent, title: 'Wat betekent: Spijtknor?', data: { slug: 'spijtknor' } },
  { path: 'blog/begrippen/spoorknor', component: BlogTermComponent, title: 'Wat betekent: Spoorknor?', data: { slug: 'spoorknor' } },
  { path: 'blog/begrippen/stiften', component: BlogTermComponent, title: 'Wat betekent: Stiften?', data: { slug: 'stiften' } },
  { path: 'blog/begrippen/strepen', component: BlogTermComponent, title: 'Wat betekent: Strepen?', data: { slug: 'strepen' } },
  { path: 'blog/begrippen/student', component: BlogTermComponent, title: 'Wat betekent: Student?', data: { slug: 'student' } },
  { path: 'blog/begrippen/studentenhuis', component: BlogTermComponent, title: 'Wat betekent: Studentenhuis?', data: { slug: 'studentenhuis' } },
  { path: 'blog/begrippen/studentenreisproduct', component: BlogTermComponent, title: 'Wat betekent: Studentenreisproduct?', data: { slug: 'studentenreisproduct' } },
  { path: 'blog/begrippen/studententien', component: BlogTermComponent, title: 'Wat betekent: Studententien?', data: { slug: 'studententien' } },
  { path: 'blog/begrippen/studentenvereniging', component: BlogTermComponent, title: 'Wat betekent: Studentenvereniging?', data: { slug: 'studentenvereniging' } },
  { path: 'blog/begrippen/studentikoos', component: BlogTermComponent, title: 'Wat betekent: Studentikoos?', data: { slug: 'studentikoos' } },
  { path: 'blog/begrippen/studievereniging', component: BlogTermComponent, title: 'Wat betekent: Studievereniging?', data: { slug: 'studievereniging' } },
  { path: 'blog/begrippen/stufi', component: BlogTermComponent, title: 'Wat betekent: Stufi?', data: { slug: 'stufi' } },
  { path: 'blog/begrippen/stuko', component: BlogTermComponent, title: 'Wat betekent: Stuko?', data: { slug: 'stuko' } },
  { path: 'blog/begrippen/super', component: BlogTermComponent, title: 'Wat betekent: De super?', data: { slug: 'super' } },
  { path: 'blog/begrippen/sws', component: BlogTermComponent, title: 'Wat betekent: SWS?', data: { slug: 'sws' } },
  { path: 'blog/begrippen/tea', component: BlogTermComponent, title: 'Wat betekent: Tea?', data: { slug: 'tea' } },
  { path: 'blog/begrippen/tellie', component: BlogTermComponent, title: 'Wat betekent: Tellie?', data: { slug: 'tellie' } },
  { path: 'blog/begrippen/tenta', component: BlogTermComponent, title: 'Wat betekent: Tenta?', data: { slug: 'tenta' } },
  { path: 'blog/begrippen/thth', component: BlogTermComponent, title: 'Wat betekent: THTH?', data: { slug: 'thth' } },
  { path: 'blog/begrippen/thuis', component: BlogTermComponent, title: 'Wat betekent: Thuis?', data: { slug: 'thuis' } },
  { path: 'blog/begrippen/thuisthuis', component: BlogTermComponent, title: 'Wat betekent: Thuisthuis?', data: { slug: 'thuisthuis' } },
  { path: 'blog/begrippen/tijgerpunten', component: BlogTermComponent, title: 'Wat betekent: Tijgerpunten?', data: { slug: 'tijgerpunten' } },
  { path: 'blog/begrippen/tjak', component: BlogTermComponent, title: 'Wat betekent: Tjak?', data: { slug: 'tjak' } },
  { path: 'blog/begrippen/tmi', component: BlogTermComponent, title: 'Wat betekent: TMI?', data: { slug: 'tmi' } },
  { path: 'blog/begrippen/toko', component: BlogTermComponent, title: 'Wat betekent: Toko?', data: { slug: 'toko' } },
  { path: 'blog/begrippen/tranqi', component: BlogTermComponent, title: 'Wat betekent: Tranqi?', data: { slug: 'tranqi' } },
  { path: 'blog/begrippen/tranquilo', component: BlogTermComponent, title: 'Wat betekent: Tranquilo?', data: { slug: 'tranquilo' } },
  { path: 'blog/begrippen/trekken', component: BlogTermComponent, title: 'Wat betekent: Trekken?', data: { slug: 'trekken' } },
  { path: 'blog/begrippen/turflijst', component: BlogTermComponent, title: 'Wat betekent: Turflijst?', data: { slug: 'turflijst' } },
  { path: 'blog/begrippen/tetteren', component: BlogTermComponent, title: 'Wat betekent: Tetteren?', data: { slug: 'tetteren' } },
  { path: 'blog/begrippen/ub', component: BlogTermComponent, title: 'Wat betekent: UB?', data: { slug: 'ub' } },
  { path: 'blog/begrippen/uf', component: BlogTermComponent, title: 'Wat betekent: Uf?', data: { slug: 'uf' } },
  { path: 'blog/begrippen/vanaaf', component: BlogTermComponent, title: 'Wat betekent: Vanaaf?', data: { slug: 'vanaaf' } },
  { path: 'blog/begrippen/vestjeslikker', component: BlogTermComponent, title: 'Wat betekent: Vestjeslikker?', data: { slug: 'vestjeslikker' } },
  { path: 'blog/begrippen/veto', component: BlogTermComponent, title: 'Wat betekent: Veto?', data: { slug: 'veto' } },
  { path: 'blog/begrippen/vino', component: BlogTermComponent, title: 'Wat betekent: Vino?', data: { slug: 'vino' } },
  { path: 'blog/begrippen/vo', component: BlogTermComponent, title: 'Wat betekent: Vo?', data: { slug: 'vo' } },
  { path: 'blog/begrippen/vozen', component: BlogTermComponent, title: 'Wat betekent: Vozen?', data: { slug: 'vozen' } },
  { path: 'blog/begrippen/vrijmibo', component: BlogTermComponent, title: 'Wat betekent: Vrijmibo?', data: { slug: 'vrijmibo' } },
  { path: 'blog/begrippen/vvv', component: BlogTermComponent, title: 'Wat betekent: VVV\'tje?', data: { slug: 'vvv' } },
  { path: 'blog/begrippen/wegtikken', component: BlogTermComponent, title: 'Wat betekent: Wegtikken?', data: { slug: 'wegtikken' } },
  { path: 'blog/begrippen/wingman', component: BlogTermComponent, title: 'Wat betekent: Wingman?', data: { slug: 'wingman' } },
  { path: 'blog/begrippen/x', component: BlogTermComponent, title: 'Wat betekent: X?', data: { slug: 'x' } },
  { path: 'blog/begrippen/zeester', component: BlogTermComponent, title: 'Wat betekent: Zeester?', data: { slug: 'zeester' } },
  { path: '**', component: NotFoundComponent, title: '404 Niet gevonden' }
];
